import { createClient } from '@supabase/supabase-js'
// NOTE: @supabase/supabase-js's typed-query generics (select-string
// parsing, relationship resolution, etc.) are designed to consume
// types generated by `supabase gen types` against a live project. Our
// hand-written src/types/database.ts models the same tables/columns
// for the rest of the app to import and annotate state with, but is
// deliberately NOT passed as the client's generic — attempting that
// against supabase-js 2.x's current type-level query parser produces
// false '`never`' errors unrelated to any real bug. Once this project
// is linked to a real Supabase instance, regenerate database.ts with
// the CLI and re-introduce `createClient<Database>(...)` then.

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined

export const isSupabaseConfigured = Boolean(supabaseUrl && supabaseAnonKey)

if (!isSupabaseConfigured) {
  console.error(
    'Talpyn: VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY жоқ. .env файлын .env.example бойынша толтырыңыз.'
  )
}

export const supabase = createClient(supabaseUrl ?? 'https://placeholder.supabase.co', supabaseAnonKey ?? 'placeholder', {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
})
