-- Generated by scripts/generateLessonSeed.ts from src/data/lessonContent/grade1Logic.ts.
-- Do not hand-edit — change the content module and regenerate instead.
-- ==== Заттарды санау (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Заттарды бір-бірлеп санап, жалпы санын дұрыс анықтай білу.' where title = 'Заттарды санау' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Талпын базарға барды. Ол алма, алмұрт, жаңғақ санауды үйретеді.', 'Заттарды санағанда әр затқа бір сан сәйкес келеді: бір, екі, үш...', 'Соңғы айтылған сан — заттардың жалпы саны.')), 0 from public.topics where title = 'Заттарды санау' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Талпынның себетіндегі алмаларды бір-бірлеп санап шық.', jsonb_build_object('kind', 'count-click', 'icon', 'apple', 'count', 6), 0 from public.topics where title = 'Заттарды санау' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Заттарды санағанда неліктен әр затты бір рет қана санаймыз?', 0 from public.topics where title = 'Заттарды санау' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Үстелде 4 кітап, 3 дәптер жатыр. Үстелде барлығы неше зат бар?', '{}'::jsonb, 0 from public.topics where title = 'Заттарды санау' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Үстелде 4 кітап, 3 дәптер жатыр. Үстелде барлығы неше зат бар?', 'short_answer', '7'::jsonb, '4 + 3 = 7.', '4 пен 3-ті қос.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Заттарды санау' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Есепте', '5 қалам мен 2 сызғыш бар. Барлығы неше зат?', 0 from public.topics where title = 'Заттарды санау' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5 қалам мен 2 сызғыш бар. Барлығы неше зат?', 'short_answer', '7'::jsonb, '5 + 2 = 7.', '5-ке 2-ні қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Заттарды санау' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Дұрыс санды тап', 'Суретте 8 зат бар делік. Дұрыс санды таңда.', 1 from public.topics where title = 'Заттарды санау' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Суретте 8 зат бар делік. Дұрыс санды таңда.', 'multiple_choice', '"8"'::jsonb, 'Сурет бойынша заттар саны 8.', 'Мұқият сана.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Заттарды санау' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('8', true, 0), ('6', false, 1), ('10', false, 2), ('7', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Заттарды санау' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Топтарды қос', '3 доп пен 4 доп қосылды. Барлығы неше доп?', 2 from public.topics where title = 'Заттарды санау' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3 доп пен 4 доп қосылды. Барлығы неше доп?', 'short_answer', '7'::jsonb, '3 + 4 = 7.', '3-ке 4-ті қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Заттарды санау' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'ordering', 'Ретімен тіз', 'Заттар топтарының санын өсу ретімен тіз:', jsonb_build_object('items', jsonb_build_array('3', '5', '7', '9')), 3 from public.topics where title = 'Заттарды санау' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 7 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(5,2), jsonb_build_array(3,4), jsonb_build_array(6,1), jsonb_build_array(4,3))), 4 from public.topics where title = 'Заттарды санау' and grade = 1 and track = 'logic';


-- ==== Заттарды салыстыру (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Заттар топтарын санына қарай салыстырып, «көп», «аз», «тең» ұғымдарын қолдана білу.' where title = 'Заттарды салыстыру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Талпын екі топ жаңғақты салыстырады.', '«Көп», «аз», «тең» дегенді біз заттардың санын салыстыру арқылы білеміз.')), 0 from public.topics where title = 'Заттарды салыстыру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Жұлдыздар мен доптардың санын салыстыр.', jsonb_build_object('kind', 'compare', 'iconA', 'star', 'countA', 5, 'iconB', 'ball', 'countB', 3), 0 from public.topics where title = 'Заттарды салыстыру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Екі топты салыстырғанда алдымен нені анықтау керек?', 0 from public.topics where title = 'Заттарды салыстыру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Айгүлде 6 қарындаш, Асанда 4 қарындаш бар. Айгүлде неше қарындаш артық?', '{}'::jsonb, 0 from public.topics where title = 'Заттарды салыстыру' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Айгүлде 6 қарындаш, Асанда 4 қарындаш бар. Айгүлде неше қарындаш артық?', 'short_answer', '2'::jsonb, '6 − 4 = 2.', '6-дан 4-ті азайт.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Заттарды салыстыру' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Айырманы тап', '9 бен 5-тің айырмасы неше?', 0 from public.topics where title = 'Заттарды салыстыру' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '9 бен 5-тің айырмасы неше?', 'short_answer', '4'::jsonb, '9 − 5 = 4.', '9-нан 5-ті азайт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Заттарды салыстыру' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Белгіні таңда', '7 мен 7 санын салыстырса, қандай белгі қойылады?', 1 from public.topics where title = 'Заттарды салыстыру' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '7 мен 7 санын салыстырса, қандай белгі қойылады?', 'multiple_choice', '"="'::jsonb, 'Сандар бірдей болса, «=» белгісі қойылады.', 'Екі сан да бірдей ме?', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Заттарды салыстыру' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('=', true, 0), ('>', false, 1), ('<', false, 2), ('≠', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Заттарды салыстыру' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Айырманы тап', '3 алма мен 8 алманың айырмасы неше?', 2 from public.topics where title = 'Заттарды салыстыру' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3 алма мен 8 алманың айырмасы неше?', 'short_answer', '5'::jsonb, '8 − 3 = 5.', '8-ден 3-ті азайт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Заттарды салыстыру' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'drag_drop', 'Топтастыр', 'Салыстыруларды «көп» және «аз» топтарына бөл:', jsonb_build_object('items', jsonb_build_array(jsonb_build_object('label', '6 > 4', 'group', 'a'), jsonb_build_object('label', '2 < 5', 'group', 'b'), jsonb_build_object('label', '9 > 3', 'group', 'a'), jsonb_build_object('label', '1 < 8', 'group', 'b')), 'groupALabel', 'Көп (>)', 'groupBLabel', 'Аз (<)'), 3 from public.topics where title = 'Заттарды салыстыру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 9 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(6,3), jsonb_build_array(7,2), jsonb_build_array(4,5), jsonb_build_array(8,1))), 4 from public.topics where title = 'Заттарды салыстыру' and grade = 1 and track = 'logic';


-- ==== Біріктіру және бөліп алу (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Заттар топтарын біріктіру және бөліп алу амалдарын түсініп қолдана білу.' where title = 'Біріктіру және бөліп алу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Талпын екі топ затты біріктіріп, жаңа топ жасайды.', 'Ал топтан бір бөлігін алып тастаса — бөліп алу деп аталады.')), 0 from public.topics where title = 'Біріктіру және бөліп алу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', null, jsonb_build_object('total', 8, 'startLeft', 5), 0 from public.topics where title = 'Біріктіру және бөліп алу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Біріктіру мен бөліп алудың айырмашылығы неде?', 0 from public.topics where title = 'Біріктіру және бөліп алу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Себетте 8 алма бар. 3-еуін алып қойдық. Қалғаны неше?', '{}'::jsonb, 0 from public.topics where title = 'Біріктіру және бөліп алу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Себетте 8 алма бар. 3-еуін алып қойдық. Қалғаны неше?', 'short_answer', '5'::jsonb, '8 − 3 = 5.', '8-ден 3-ті азайт.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Біріктіру және бөліп алу' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Біріктір', '6 бен 2-ні біріктір.', 0 from public.topics where title = 'Біріктіру және бөліп алу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '6 бен 2-ні біріктір.', 'short_answer', '8'::jsonb, '6 + 2 = 8.', '6-ға 2-ні қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Біріктіру және бөліп алу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Бөліп ал', '9-дан 4-ті бөліп ал, қалғаны неше?', 1 from public.topics where title = 'Біріктіру және бөліп алу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '9-дан 4-ті бөліп ал, қалғаны неше?', 'short_answer', '5'::jsonb, '9 − 4 = 5.', '9-нан 4-ті азайт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Біріктіру және бөліп алу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Амалды тап', '«Біріктіру» сөзіне сәйкес амалды таңда.', 2 from public.topics where title = 'Біріктіру және бөліп алу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '«Біріктіру» сөзіне сәйкес амалды таңда.', 'multiple_choice', '"+"'::jsonb, 'Біріктіру — қосу амалы.', 'Топтарды қосамыз ба, азайтамыз ба?', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Біріктіру және бөліп алу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('+', true, 0), ('−', false, 1), ('×', false, 2), ('÷', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Біріктіру және бөліп алу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', 'Есептеу қадамдарының қайсысында қате бар?', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('6 + 2 = 8', '8 − 3 = 5', '5 + 1 = 7'), 'errorIndex', 2), 3 from public.topics where title = 'Біріктіру және бөліп алу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Есептеу қадамдарының қайсысында қате бар?', 'find_error', '2'::jsonb, 'Дұрысы: 5 + 1 = 6.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Біріктіру және бөліп алу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 8 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(6,2), jsonb_build_array(5,3), jsonb_build_array(7,1), jsonb_build_array(4,4))), 4 from public.topics where title = 'Біріктіру және бөліп алу' and grade = 1 and track = 'logic';


-- ==== Мөлшер және сан (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Заттар мөлшерін санмен өрнектей білу.' where title = 'Мөлшер және сан' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Мөлшер — заттың қаншалығы. Сан — сол мөлшерді белгілейтін таңба.', 'Талпын көлдегі балықтарды санап, мөлшерін санмен жазады.')), 0 from public.topics where title = 'Мөлшер және сан' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Талпын көлдегі балықтарды санайды, сен де сана.', jsonb_build_object('kind', 'count-click', 'icon', 'fish', 'count', 7), 0 from public.topics where title = 'Мөлшер және сан' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Сан мен мөлшердің байланысы қандай?', 0 from public.topics where title = 'Мөлшер және сан' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Аквариумда 7 балық бар еді, 2-уі басқа аквариумға ауысты. Қанша балық қалды?', '{}'::jsonb, 0 from public.topics where title = 'Мөлшер және сан' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Аквариумда 7 балық бар еді, 2-уі басқа аквариумға ауысты. Қанша балық қалды?', 'short_answer', '5'::jsonb, '7 − 2 = 5.', '7-ден 2-ні азайт.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Мөлшер және сан' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Қос', '4 пен 3-ті қос.', 0 from public.topics where title = 'Мөлшер және сан' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '4 пен 3-ті қос.', 'short_answer', '7'::jsonb, '4 + 3 = 7.', '4-ке 3-ті қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Мөлшер және сан' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Түсінікті тап', '«Мөлшер» сөзі нені білдіреді?', 1 from public.topics where title = 'Мөлшер және сан' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '«Мөлшер» сөзі нені білдіреді?', 'multiple_choice', '"заттың санын/шамасын"'::jsonb, 'Мөлшер — заттың саны немесе шамасы.', 'Мөлшер сан арқылы өлшенеді.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Мөлшер және сан' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('заттың санын/шамасын', true, 0), ('заттың түсін', false, 1), ('заттың дәмін', false, 2), ('заттың атауын', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Мөлшер және сан' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Азайт', '9 балықтың 4-уі кетті. Қалғаны неше?', 2 from public.topics where title = 'Мөлшер және сан' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '9 балықтың 4-уі кетті. Қалғаны неше?', 'short_answer', '5'::jsonb, '9 − 4 = 5.', '9-нан 4-ті азайт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Мөлшер және сан' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'drag_drop', 'Топтастыр', 'Сандарды «5-тен аз» және «5-тен көп» топтарына бөл:', jsonb_build_object('items', jsonb_build_array(jsonb_build_object('label', '2', 'group', 'a'), jsonb_build_object('label', '8', 'group', 'b'), jsonb_build_object('label', '4', 'group', 'a'), jsonb_build_object('label', '9', 'group', 'b')), 'groupALabel', '5-тен аз', 'groupBLabel', '5-тен көп'), 3 from public.topics where title = 'Мөлшер және сан' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 7 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(2,5), jsonb_build_array(6,1), jsonb_build_array(4,3), jsonb_build_array(3,4))), 4 from public.topics where title = 'Мөлшер және сан' and grade = 1 and track = 'logic';


-- ==== 1–10 көлеміндегі сандар (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = '1-ден 10-ға дейінгі сандар тізбегін еркін меңгеру.' where title = '1–10 көлеміндегі сандар' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('1-ден 10-ға дейінгі сандар — санаудың негізгі тізбегі.', 'Талпын әр санды кезекпен атайды: бір, екі, үш... он.')), 0 from public.topics where title = '1–10 көлеміндегі сандар' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Санды тізбекті толтыр.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('1', '2', '3', '?', '5', '6'), 'blankIndex', 3, 'correctValue', '4'), 0 from public.topics where title = '1–10 көлеміндегі сандар' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', '1-ден 10-ға дейінгі тізбекте әрбір келесі сан алдыңғыдан қаншаға артық?', 0 from public.topics where title = '1–10 көлеміндегі сандар' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Санауда 6-дан кейін қай сан келеді?', '{}'::jsonb, 0 from public.topics where title = '1–10 көлеміндегі сандар' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Санауда 6-дан кейін қай сан келеді?', 'short_answer', '7'::jsonb, '6-дан кейін 7 келеді.', '6-ға 1-ді қос.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = '1–10 көлеміндегі сандар' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Келесі сан', '8-ден кейінгі сан?', 0 from public.topics where title = '1–10 көлеміндегі сандар' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '8-ден кейінгі сан?', 'short_answer', '9'::jsonb, '8 + 1 = 9.', '8-ге 1-ді қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '1–10 көлеміндегі сандар' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Санды тап', '10-нан бір кем сан қайсы?', 1 from public.topics where title = '1–10 көлеміндегі сандар' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '10-нан бір кем сан қайсы?', 'multiple_choice', '"9"'::jsonb, '10 − 1 = 9.', '10-нан 1-ді азайт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '1–10 көлеміндегі сандар' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('9', true, 0), ('8', false, 1), ('11', false, 2), ('10', false, 3)) as opt(text, is_correct, ord) where t2.title = '1–10 көлеміндегі сандар' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Санды тап', '3-тен 7-ге дейін (қоса алғанда) неше сан бар?', 2 from public.topics where title = '1–10 көлеміндегі сандар' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3-тен 7-ге дейін (қоса алғанда) неше сан бар?', 'short_answer', '5'::jsonb, '3, 4, 5, 6, 7 — барлығы 5 сан.', 'Тізбектеп санап шық.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '1–10 көлеміндегі сандар' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'ordering', 'Ретімен тіз', 'Сандарды өсу ретімен тіз:', jsonb_build_object('items', jsonb_build_array('1', '2', '4', '5', '9')), 3 from public.topics where title = '1–10 көлеміндегі сандар' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 10 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(6,4), jsonb_build_array(7,3), jsonb_build_array(8,2), jsonb_build_array(9,1))), 4 from public.topics where title = '1–10 көлеміндегі сандар' and grade = 1 and track = 'logic';


-- ==== Сандар әлемі туралы ертегі (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Сандар тізбегінің реті мен орнын ертегі арқылы бекіту.' where title = 'Сандар әлемі туралы ертегі' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Ертеде сандар елінде 1-ден 10-ға дейін он бауыр өмір сүрді.', 'Әр сан өз орнында тұрды: 1 бірінші, 2 екінші, 3 үшінші...', 'Талпын осы елге саяхаттап, сандармен дос болды.')), 0 from public.topics where title = 'Сандар әлемі туралы ертегі' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Ертегі елінде жоғалып кеткен бауырды тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('1', '2', '3', '4', '?', '6', '7'), 'blankIndex', 4, 'correctValue', '5'), 0 from public.topics where title = 'Сандар әлемі туралы ертегі' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Ертегідегі сандардың реті бұзылса не болады?', 0 from public.topics where title = 'Сандар әлемі туралы ертегі' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Ертегі елінде 10 бауырдың 4-еуі ұйықтап жатыр. Ояу тұрғандары неше?', '{}'::jsonb, 0 from public.topics where title = 'Сандар әлемі туралы ертегі' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Ертегі елінде 10 бауырдың 4-еуі ұйықтап жатыр. Ояу тұрғандары неше?', 'short_answer', '6'::jsonb, '10 − 4 = 6.', '10-нан 4-ті азайт.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Сандар әлемі туралы ертегі' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Кезекті тап', 'Ертегідегі 7-ші бауырдан кейін нешінші бауыр келеді?', 0 from public.topics where title = 'Сандар әлемі туралы ертегі' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Ертегідегі 7-ші бауырдан кейін нешінші бауыр келеді?', 'short_answer', '8'::jsonb, '7-ден кейін 8-ші келеді.', '7-ге 1-ді қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сандар әлемі туралы ертегі' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Санын тап', 'Ертегі елінде барлығы неше сан-бауыр өмір сүрді?', 1 from public.topics where title = 'Сандар әлемі туралы ертегі' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Ертегі елінде барлығы неше сан-бауыр өмір сүрді?', 'multiple_choice', '"10"'::jsonb, 'Ертегіде 1-ден 10-ға дейінгі он бауыр болды.', '1-ден 10-ға дейін санап шық.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сандар әлемі туралы ертегі' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('10', true, 0), ('9', false, 1), ('11', false, 2), ('8', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Сандар әлемі туралы ертегі' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Ортаншы бауыр', '1-ден 9-ға дейінгі бауырлардың ең ортаншысы нешінші?', 2 from public.topics where title = 'Сандар әлемі туралы ертегі' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '1-ден 9-ға дейінгі бауырлардың ең ортаншысы нешінші?', 'short_answer', '5'::jsonb, '1..9 тізбегінің ортасы — 5.', 'Тізбекті екіге бөліп қара.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сандар әлемі туралы ертегі' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'ordering', 'Ретімен тіз', 'Бауырлардың нөмірлерін өсу ретімен тіз:', jsonb_build_object('items', jsonb_build_array('1', '3', '6', '9')), 3 from public.topics where title = 'Сандар әлемі туралы ертегі' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 10 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(5,5), jsonb_build_array(6,4), jsonb_build_array(3,7), jsonb_build_array(2,8))), 4 from public.topics where title = 'Сандар әлемі туралы ертегі' and grade = 1 and track = 'logic';


-- ==== Сан және санау (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = '«Сан» мен «санау» ұғымдарын ажырата білу.' where title = 'Сан және санау' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('«Санау» — заттарды бір-бірлеп есептеу үдерісі.', '«Сан» — сол санаудың нәтижесін білдіретін таңба.')), 0 from public.topics where title = 'Сан және санау' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Ағаштан түскен жапырақтарды санап шық.', jsonb_build_object('kind', 'count-click', 'icon', 'leaf', 'count', 9), 0 from public.topics where title = 'Сан және санау' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Сан мен санаудың айырмашылығы неде?', 0 from public.topics where title = 'Сан және санау' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Ағаштан 9 жапырақ түсті, желмен 3-еуі ұшып кетті. Қалғаны неше?', '{}'::jsonb, 0 from public.topics where title = 'Сан және санау' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Ағаштан 9 жапырақ түсті, желмен 3-еуі ұшып кетті. Қалғаны неше?', 'short_answer', '6'::jsonb, '9 − 3 = 6.', '9-нан 3-ті азайт.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Сан және санау' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Қос', '5 бен 4-ті қос.', 0 from public.topics where title = 'Сан және санау' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5 бен 4-ті қос.', 'short_answer', '9'::jsonb, '5 + 4 = 9.', '5-ке 4-ті қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сан және санау' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Анықтаманы тап', '«Санау» деген не?', 1 from public.topics where title = 'Сан және санау' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '«Санау» деген не?', 'multiple_choice', '"заттарды бір-бірлеп есептеу"'::jsonb, 'Санау — заттарды ретімен бір-бірлеп есептеу.', 'Санау — бұл әрекет пе, әлде таңба ма?', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сан және санау' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('заттарды бір-бірлеп есептеу', true, 0), ('затты бояу', false, 1), ('затты өлшеу', false, 2), ('затты жинау', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Сан және санау' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Азайт', '9-дан 3-ті азайт.', 2 from public.topics where title = 'Сан және санау' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '9-дан 3-ті азайт.', 'short_answer', '6'::jsonb, '9 − 3 = 6.', '9-нан 3-ті кемiт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сан және санау' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'drag_drop', 'Топтастыр', '«Санау» (әрекет) пен «сан» (таңба) мысалдарын топтастыр:', jsonb_build_object('items', jsonb_build_array(jsonb_build_object('label', 'Заттарды бір-бірлеп есептеу', 'group', 'a'), jsonb_build_object('label', '«7» таңбасы', 'group', 'b'), jsonb_build_object('label', 'Топтағы алманы санау', 'group', 'a'), jsonb_build_object('label', '«12» саны', 'group', 'b')), 'groupALabel', 'Санау (әрекет)', 'groupBLabel', 'Сан (таңба)'), 3 from public.topics where title = 'Сан және санау' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 9 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(5,4), jsonb_build_array(6,3), jsonb_build_array(7,2), jsonb_build_array(8,1))), 4 from public.topics where title = 'Сан және санау' and grade = 1 and track = 'logic';


-- ==== Неше? Нешінші? (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Сан мөлшерін (неше?) мен реттік орнын (нешінші?) ажырата білу.' where title = 'Неше? Нешінші?' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('«Неше?» сұрағы заттардың санын сұрайды.', '«Нешінші?» сұрағы заттың кезектегі орнын сұрайды.')), 0 from public.topics where title = 'Неше? Нешінші?' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', '4-ші текшені тап.', jsonb_build_object('kind', 'ordinal', 'icon', 'cube', 'count', 6, 'targetPosition', 4), 0 from public.topics where title = 'Неше? Нешінші?' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', '«Неше?» және «нешінші?» сұрақтарының айырмашылығы неде?', 0 from public.topics where title = 'Неше? Нешінші?' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Кезекте 6 бала тұр. Айгүл 3-ші орында. Айгүлден кейін неше бала тұр?', '{}'::jsonb, 0 from public.topics where title = 'Неше? Нешінші?' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Кезекте 6 бала тұр. Айгүл 3-ші орында. Айгүлден кейін неше бала тұр?', 'short_answer', '3'::jsonb, '6 − 3 = 3.', '6-дан 3-ті азайт.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Неше? Нешінші?' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Орнын тап', 'Кезекте 7 адам бар. Соңғысы нешінші?', 0 from public.topics where title = 'Неше? Нешінші?' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Кезекте 7 адам бар. Соңғысы нешінші?', 'short_answer', '7'::jsonb, 'Соңғы адам — 7-ші орында.', 'Барлық адам санымен бірдей.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Неше? Нешінші?' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Сұрақ түрін тап', '«Неше?» сұрағы нені білдіреді?', 1 from public.topics where title = 'Неше? Нешінші?' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '«Неше?» сұрағы нені білдіреді?', 'multiple_choice', '"сан (мөлшер)"'::jsonb, '«Неше?» — мөлшерді сұрайды.', '«Нешінші?» орынды сұрайды, ал «неше?»...', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Неше? Нешінші?' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('сан (мөлшер)', true, 0), ('орын (реті)', false, 1), ('түс', false, 2), ('өлшем', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Неше? Нешінші?' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Кезекті тап', '5-ші орындағыдан кейінгі бала нешінші?', 2 from public.topics where title = 'Неше? Нешінші?' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5-ші орындағыдан кейінгі бала нешінші?', 'short_answer', '6'::jsonb, '5-тен кейін 6-шы келеді.', '5-ке 1-ді қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Неше? Нешінші?' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'drag_drop', 'Сұрақ түрін ажырат', 'Сұрақтарды «неше?» және «нешінші?» топтарына бөл:', jsonb_build_object('items', jsonb_build_array(jsonb_build_object('label', 'Үстелде неше кітап бар?', 'group', 'a'), jsonb_build_object('label', 'Ол кезекте нешінші тұр?', 'group', 'b'), jsonb_build_object('label', 'Себетте неше алма бар?', 'group', 'a'), jsonb_build_object('label', 'Ол жарыста нешінші орын алды?', 'group', 'b')), 'groupALabel', '«Неше?» (мөлшер)', 'groupBLabel', '«Нешінші?» (орын)'), 3 from public.topics where title = 'Неше? Нешінші?' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 10 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(4,6), jsonb_build_array(5,5), jsonb_build_array(3,7), jsonb_build_array(2,8))), 4 from public.topics where title = 'Неше? Нешінші?' and grade = 1 and track = 'logic';


-- ==== Сандар тізбегінен заңдылықты табу (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Сандар тізбегіндегі заңдылықты байқап, жетіспейтін санды таба білу.' where title = 'Сандар тізбегінен заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Талпын байқаған: көптеген тізбектерде сандар белгілі бір ретпен өзгереді.', 'Осы ретті тауып алсақ, келесі санды болжай аламыз.')), 0 from public.topics where title = 'Сандар тізбегінен заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Заңдылықты тауып, жетіспейтін санды тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('2', '4', '6', '?', '10'), 'blankIndex', 3, 'correctValue', '8'), 0 from public.topics where title = 'Сандар тізбегінен заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Бұл тізбекте сандар неше-неше өседі?', 0 from public.topics where title = 'Сандар тізбегінен заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '3, 6, 9, 12, ? тізбегінде келесі сан неше?', '{}'::jsonb, 0 from public.topics where title = 'Сандар тізбегінен заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3, 6, 9, 12, ? тізбегінде келесі сан неше?', 'short_answer', '15'::jsonb, 'Тізбек 3-тен өседі: 12 + 3 = 15.', 'Әр санға 3-ті қос.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Сандар тізбегінен заңдылықты табу' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Заңдылықты тап', '1, 3, 5, 7, ? тізбегіндегі келесі сан?', 0 from public.topics where title = 'Сандар тізбегінен заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '1, 3, 5, 7, ? тізбегіндегі келесі сан?', 'short_answer', '9'::jsonb, '7 + 2 = 9.', 'Тізбек 2-ден өседі.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сандар тізбегінен заңдылықты табу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Жетіспейтін санды тап', '10, 8, 6, ?, 2 тізбегіндегі жетіспейтін сан?', 1 from public.topics where title = 'Сандар тізбегінен заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '10, 8, 6, ?, 2 тізбегіндегі жетіспейтін сан?', 'multiple_choice', '"4"'::jsonb, 'Тізбек 2-ден кемиді: 6 − 2 = 4.', 'Тізбек кему ретімен келеді.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сандар тізбегінен заңдылықты табу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('4', true, 0), ('5', false, 1), ('3', false, 2), ('6', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Сандар тізбегінен заңдылықты табу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Заңдылықты тап', '5, 10, 15, ?, 25 тізбегіндегі жетіспейтін сан?', 2 from public.topics where title = 'Сандар тізбегінен заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5, 10, 15, ?, 25 тізбегіндегі жетіспейтін сан?', 'short_answer', '20'::jsonb, 'Тізбек 5-тен өседі: 15 + 5 = 20.', 'Әр санға 5-ті қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сандар тізбегінен заңдылықты табу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', 'Тізбектердің заңдылығы қай жолда қате көрсетілген?', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('2, 4, 6, 8, 10 — әрбір сан 2-ге өседі', '1, 3, 5, 7 — әрбір сан 2-ге өседі', '5, 10, 15, 20 — әрбір сан 4-ке өседі'), 'errorIndex', 2), 3 from public.topics where title = 'Сандар тізбегінен заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Тізбектердің заңдылығы қай жолда қате көрсетілген?', 'find_error', '2'::jsonb, 'Дұрысы: 5, 10, 15, 20 тізбегінде әрбір сан 5-ке өседі.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сандар тізбегінен заңдылықты табу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 12 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(5,7), jsonb_build_array(9,3), jsonb_build_array(4,8), jsonb_build_array(6,6))), 4 from public.topics where title = 'Сандар тізбегінен заңдылықты табу' and grade = 1 and track = 'logic';


-- ==== Қарапайым фигураларды тану (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Дөңгелек, шаршы, үшбұрыш, тік төртбұрыш фигураларын тани білу.' where title = 'Қарапайым фигураларды тану' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'infographic', null, null, jsonb_build_object('kind', 'scene', 'items', jsonb_build_array(jsonb_build_object('icon', '⚪', 'label', 'Дөңгелек'), jsonb_build_object('icon', '⬛', 'label', 'Шаршы'), jsonb_build_object('icon', '🔺', 'label', 'Үшбұрыш')), 'caption', 'Талпынмен бірге қарапайым фигураларды танимыз: дөңгелектің бұрышы жоқ, шаршының 4 тең қабырғасы мен бұрышы бар, үшбұрыштың 3 қабырғасы мен 3 бұрышы бар.'), 0 from public.topics where title = 'Қарапайым фигураларды тану' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Үшбұрышты тап.', jsonb_build_object('kind', 'shape-match', 'shapes', jsonb_build_array('circle', 'square', 'triangle', 'star'), 'targetShape', 'triangle'), 0 from public.topics where title = 'Қарапайым фигураларды тану' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Дөңгелек пен шаршының айырмашылығы неде?', 0 from public.topics where title = 'Қарапайым фигураларды тану' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Бөлмеде 2 дөңгелек, 3 шаршы зат бар. Барлығы неше фигура бар?', '{}'::jsonb, 0 from public.topics where title = 'Қарапайым фигураларды тану' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Бөлмеде 2 дөңгелек, 3 шаршы зат бар. Барлығы неше фигура бар?', 'short_answer', '5'::jsonb, '2 + 3 = 5.', '2-ге 3-ті қос.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Қарапайым фигураларды тану' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Фигураны тап', '3 бұрышы бар фигураның атауы?', 0 from public.topics where title = 'Қарапайым фигураларды тану' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3 бұрышы бар фигураның атауы?', 'short_answer', '"үшбұрыш"'::jsonb, '3 бұрышы бар фигура — үшбұрыш.', 'Бұрыштарын санап көр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қарапайым фигураларды тану' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Санды тап', 'Дөңгелектің неше бұрышы бар?', 1 from public.topics where title = 'Қарапайым фигураларды тану' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Дөңгелектің неше бұрышы бар?', 'multiple_choice', '"0"'::jsonb, 'Дөңгелекте бұрыш жоқ.', 'Дөңгелекті көз алдыңа елестет.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қарапайым фигураларды тану' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('0', true, 0), ('3', false, 1), ('4', false, 2), ('5', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Қарапайым фигураларды тану' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Фигураны тап', '4 тең қабырғасы бар фигура — бұл не?', 2 from public.topics where title = 'Қарапайым фигураларды тану' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '4 тең қабырғасы бар фигура — бұл не?', 'short_answer', '"шаршы"'::jsonb, '4 тең қабырғасы бар фигура — шаршы.', 'Барлық қабырғасы бірдей.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қарапайым фигураларды тану' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Фигураны атауымен сәйкестендір', 'Әр фигураны дұрыс атауымен сәйкестендір:', jsonb_build_object('kind', 'visual', 'pairs', jsonb_build_array(jsonb_build_object('icon', '⚪', 'label', 'Дөңгелек'), jsonb_build_object('icon', '⬛', 'label', 'Шаршы'), jsonb_build_object('icon', '🔺', 'label', 'Үшбұрыш'))), 3 from public.topics where title = 'Қарапайым фигураларды тану' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 10 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(7,3), jsonb_build_array(6,4), jsonb_build_array(8,2), jsonb_build_array(9,1))), 4 from public.topics where title = 'Қарапайым фигураларды тану' and grade = 1 and track = 'logic';


-- ==== Фигуралардан заңдылықты табу (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Фигуралар тізбегіндегі заңдылықты байқап, жалғастыра білу.' where title = 'Фигуралардан заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Фигуралар да сандар сияқты белгілі ретпен қайталанады.', 'Талпын фигуралар тізбегіндегі ретті тауып, жалғастырады.')), 0 from public.topics where title = 'Фигуралардан заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Фигуралар заңдылығын жалғастыр.', jsonb_build_object('kind', 'pattern-shape', 'sequence', jsonb_build_array('●', '▲', '●', '▲', '?'), 'blankIndex', 4, 'correctValue', '●'), 0 from public.topics where title = 'Фигуралардан заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Фигуралар заңдылығын қалай таптық?', 0 from public.topics where title = 'Фигуралардан заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '■●■●■? тізбегінде келесі фигура қандай (■ немесе ●)?', '{}'::jsonb, 0 from public.topics where title = 'Фигуралардан заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '■●■●■? тізбегінде келесі фигура қандай (■ немесе ●)?', 'short_answer', '"●"'::jsonb, 'Тізбек ■ мен ● кезектесіп келеді, келесі — ●.', 'Тізбектің ретін байқа.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Фигуралардан заңдылықты табу' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жалғастыр', '▲●▲●▲? — келесі фигура?', 0 from public.topics where title = 'Фигуралардан заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '▲●▲●▲? — келесі фигура?', 'short_answer', '"●"'::jsonb, 'Тізбек ▲ мен ● кезектеседі.', 'Соңғы фигура ▲ болса, келесісі...', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Фигуралардан заңдылықты табу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Жалғастыр', '★■★■★? тізбегінде келесі не?', 1 from public.topics where title = 'Фигуралардан заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '★■★■★? тізбегінде келесі не?', 'multiple_choice', '"■"'::jsonb, 'Тізбек ★ мен ■ кезектеседі.', 'Тізбектің ретін байқа.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Фигуралардан заңдылықты табу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('■', true, 0), ('★', false, 1), ('●', false, 2), ('▲', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Фигуралардан заңдылықты табу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жалғастыр', '●●▲●●▲●●? — келесі фигура?', 2 from public.topics where title = 'Фигуралардан заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '●●▲●●▲●●? — келесі фигура?', 'short_answer', '"▲"'::jsonb, 'Тізбек екі ● содан кейін бір ▲ болып қайталанады.', 'Топтарды санап көр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Фигуралардан заңдылықты табу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', 'Тізбектің жалғасы қай жолда қате көрсетілген?', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('●▲●▲● — келесі ▲', '■●■●■ — келесі ●', '★■★■★ — келесі ★'), 'errorIndex', 2), 3 from public.topics where title = 'Фигуралардан заңдылықты табу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Тізбектің жалғасы қай жолда қате көрсетілген?', 'find_error', '2'::jsonb, 'Дұрысы: ★■★■★ тізбегінде келесі фигура — ■.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Фигуралардан заңдылықты табу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 10 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(5,5), jsonb_build_array(6,4), jsonb_build_array(7,3), jsonb_build_array(8,2))), 4 from public.topics where title = 'Фигуралардан заңдылықты табу' and grade = 1 and track = 'logic';


-- ==== Сиқырлы фигураларға сандарды толтыру (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Сиқырлы шаршыда әр жолдың қосындысы бірдей болатынын түсініп, жетіспейтін сандарды таба білу.' where title = 'Сиқырлы фигураларға сандарды толтыру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Сиқырлы шаршыда әр жолдың, әр бағанның қосындысы бірдей болады.', 'Талпын мысал ретінде: 4, 9, 2 / 3, 5, 7 / 8, 1, 6 деген шаршыны көрсетеді — әр жолдың қосындысы 15.')), 0 from public.topics where title = 'Сиқырлы фигураларға сандарды толтыру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Сиқырлы шаршыдағы жетіспейтін сандарды тап.', jsonb_build_object('kind', 'magic-square', 'cells', jsonb_build_array(4, null, 2, 3, 5, 7, 8, null, 6), 'targetSum', 15), 0 from public.topics where title = 'Сиқырлы фигураларға сандарды толтыру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Сиқырлы шаршыда әр жолдың қосындысы неге бірдей болуы керек?', 0 from public.topics where title = 'Сиқырлы фигураларға сандарды толтыру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Сиқырлы шаршының бір жолында 4, 9, 2 сандары бар. Қосындысы неше?', '{}'::jsonb, 0 from public.topics where title = 'Сиқырлы фигураларға сандарды толтыру' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Сиқырлы шаршының бір жолында 4, 9, 2 сандары бар. Қосындысы неше?', 'short_answer', '15'::jsonb, '4 + 9 + 2 = 15.', 'Үш санды ретімен қос.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Сиқырлы фигураларға сандарды толтыру' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Қосындыны тап', '4 + 9 + 2 неше?', 0 from public.topics where title = 'Сиқырлы фигураларға сандарды толтыру' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '4 + 9 + 2 неше?', 'short_answer', '15'::jsonb, '4 + 9 + 2 = 15.', 'Ретімен қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сиқырлы фигураларға сандарды толтыру' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Ережені тап', 'Сиқырлы шаршыда барлық жолдың қосындысы қандай болу керек?', 1 from public.topics where title = 'Сиқырлы фигураларға сандарды толтыру' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Сиқырлы шаршыда барлық жолдың қосындысы қандай болу керек?', 'multiple_choice', '"бірдей"'::jsonb, 'Сиқырлы шаршының басты ережесі — барлық жол мен баған қосындысы бірдей.', 'Шаршыны «сиқырлы» ететін не?', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сиқырлы фигураларға сандарды толтыру' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('бірдей', true, 0), ('әр түрлі', false, 1), ('кему керек', false, 2), ('өсу керек', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Сиқырлы фигураларға сандарды толтыру' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Қосындыны тап', '3 + 5 + 7 неше?', 2 from public.topics where title = 'Сиқырлы фигураларға сандарды толтыру' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3 + 5 + 7 неше?', 'short_answer', '15'::jsonb, '3 + 5 + 7 = 15.', 'Ретімен қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сиқырлы фигураларға сандарды толтыру' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', 'Сиқырлы шаршының жолдарын тексер — қай жолда қате бар?', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('4 + 9 + 2 = 15', '3 + 5 + 7 = 15', '8 + 1 + 6 = 16'), 'errorIndex', 2), 3 from public.topics where title = 'Сиқырлы фигураларға сандарды толтыру' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Сиқырлы шаршының жолдарын тексер — қай жолда қате бар?', 'find_error', '2'::jsonb, 'Дұрысы: 8 + 1 + 6 = 15.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сиқырлы фигураларға сандарды толтыру' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 15 болатын сандарды сәйкестендір (сиқырлы шаршының жол қосындысы):', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(9,6), jsonb_build_array(11,4), jsonb_build_array(13,2), jsonb_build_array(7,8))), 4 from public.topics where title = 'Сиқырлы фигураларға сандарды толтыру' and grade = 1 and track = 'logic';


-- ==== Есептеу және сәйкестендіру (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Өрнектің мәнін есептеп, сәйкес санмен байланыстыра білу.' where title = 'Есептеу және сәйкестендіру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Талпын өрнектің мәнін есептеп, оны дұрыс санмен сәйкестендіреді.', 'Мысалы: 6 + 3 өрнегінің мәні — 9.')), 0 from public.topics where title = 'Есептеу және сәйкестендіру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', null, jsonb_build_object('total', 9, 'startLeft', 4), 0 from public.topics where title = 'Есептеу және сәйкестендіру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Есептеу мен сәйкестендірудің қандай байланысы бар?', 0 from public.topics where title = 'Есептеу және сәйкестендіру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '6 + 3 өрнегінің мәні қай санмен сәйкес келеді?', '{}'::jsonb, 0 from public.topics where title = 'Есептеу және сәйкестендіру' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '6 + 3 өрнегінің мәні қай санмен сәйкес келеді?', 'short_answer', '9'::jsonb, '6 + 3 = 9.', '6-ға 3-ті қос.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Есептеу және сәйкестендіру' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', '10-ды құрайтын жұптарды сәйкестендір', 'Әр санды жұбымен сәйкестендір (қосындысы 10)', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(2,8), jsonb_build_array(3,7), jsonb_build_array(4,6), jsonb_build_array(5,5))), 0 from public.topics where title = 'Есептеу және сәйкестендіру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Есепте', '7 + 2 неше?', 1 from public.topics where title = 'Есептеу және сәйкестендіру' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '7 + 2 неше?', 'short_answer', '9'::jsonb, '7 + 2 = 9.', '7-ге 2-ні қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Есептеу және сәйкестендіру' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Мәнін тап', '5 + 4 нешеге тең?', 2 from public.topics where title = 'Есептеу және сәйкестендіру' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5 + 4 нешеге тең?', 'multiple_choice', '"9"'::jsonb, '5 + 4 = 9.', '5-ке 4-ті қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Есептеу және сәйкестендіру' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('9', true, 0), ('8', false, 1), ('10', false, 2), ('7', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Есептеу және сәйкестендіру' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'ordering', 'Мәні бойынша тіз', 'Өрнектерді мәні бойынша өсу ретімен тіз:', jsonb_build_object('items', jsonb_build_array('3 + 2', '4 + 4', '6 + 3')), 3 from public.topics where title = 'Есептеу және сәйкестендіру' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', '5 + 4 өрнегінің сәйкестендірілуін тексер.', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('5 + 4 = 8', 'Сәйкес сан — 8'), 'errorIndex', 0), 4 from public.topics where title = 'Есептеу және сәйкестендіру' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5 + 4 өрнегінің сәйкестендірілуін тексер.', 'find_error', '0'::jsonb, '5 + 4 = 9, 8 емес.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Есептеу және сәйкестендіру' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 4;


-- ==== Мәтін есептер (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Мәтін есептің шартын, сұрағын анықтап, дұрыс амалмен шығара білу.' where title = 'Мәтін есептер' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Мәтін есепте алдымен шартын оқимыз, содан кейін сұрағын анықтаймыз.', 'Талпын: «Шартты түсінбей есепті шығаруға болмайды!»')), 0 from public.topics where title = 'Мәтін есептер' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', null, jsonb_build_object('total', 10, 'startLeft', 6), 0 from public.topics where title = 'Мәтін есептер' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Мәтін есепті шешу үшін алдымен нені анықтау керек?', 0 from public.topics where title = 'Мәтін есептер' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Азаматта 5 шар бар еді. Досы оған 3 шар берді. Азаматта қазір неше шар бар?', '{}'::jsonb, 0 from public.topics where title = 'Мәтін есептер' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Азаматта 5 шар бар еді. Досы оған 3 шар берді. Азаматта қазір неше шар бар?', 'short_answer', '8'::jsonb, '5 + 3 = 8.', '5-ке 3-ті қос.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Мәтін есептер' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Есепті шығар', 'Дүкенде 6 нан бар еді, 2-уін сатып алды. Қалғаны неше?', 0 from public.topics where title = 'Мәтін есептер' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Дүкенде 6 нан бар еді, 2-уін сатып алды. Қалғаны неше?', 'short_answer', '4'::jsonb, '6 − 2 = 4.', '6-дан 2-ні азайт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Мәтін есептер' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Ретті тап', 'Есепті шығарар алдында бірінші не істейміз?', 1 from public.topics where title = 'Мәтін есептер' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Есепті шығарар алдында бірінші не істейміз?', 'multiple_choice', '"шартын оқимыз"'::jsonb, 'Есепті шығарудың алғашқы қадамы — шартын мұқият оқып түсіну.', 'Шартын түсінбей шешім таба аласың ба?', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Мәтін есептер' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('шартын оқимыз', true, 0), ('жауабын жазамыз', false, 1), ('суретін саламыз', false, 2), ('ұмытамыз', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Мәтін есептер' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Есепті шығар', 'Ару 4 алма терді, Гүлмен 3 алма терді. Екеуі бірге неше алма терді?', 2 from public.topics where title = 'Мәтін есептер' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Ару 4 алма терді, Гүлмен 3 алма терді. Екеуі бірге неше алма терді?', 'short_answer', '7'::jsonb, '4 + 3 = 7.', '4-ке 3-ті қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Мәтін есептер' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'drag_drop', 'Амалды таңда', 'Есептерді қандай амал керек екеніне қарай екі топқа бөл:', jsonb_build_object('items', jsonb_build_array(jsonb_build_object('label', 'Бар еді, тағы берді', 'group', 'a'), jsonb_build_object('label', 'Бар еді, сатып алды (кетті)', 'group', 'b'), jsonb_build_object('label', 'Екеуі бірге терді', 'group', 'a'), jsonb_build_object('label', 'Ұшып кетті', 'group', 'b')), 'groupALabel', 'Қосу керек (+)', 'groupBLabel', 'Азайту керек (−)'), 3 from public.topics where title = 'Мәтін есептер' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 8 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(5,3), jsonb_build_array(6,2), jsonb_build_array(7,1), jsonb_build_array(4,4))), 4 from public.topics where title = 'Мәтін есептер' and grade = 1 and track = 'logic';


-- ==== Жылдам есептеу (1-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Қосу мен азайтуды жылдам әрі дұрыс орындай білу.' where title = 'Жылдам есептеу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Жылдам есептеу үшін 10-ға толықтыру тәсілін пайдалануға болады.', 'Талпын: «Жаттыққан сайын жылдамырақ есептейсің!»')), 0 from public.topics where title = 'Жылдам есептеу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', null, jsonb_build_object('total', 10, 'startLeft', 7), 0 from public.topics where title = 'Жылдам есептеу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Жылдам есептеу үшін қандай тәсіл қолдануға болады?', 0 from public.topics where title = 'Жылдам есептеу' and grade = 1 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '9 + 1 неше?', '{}'::jsonb, 0 from public.topics where title = 'Жылдам есептеу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '9 + 1 неше?', 'short_answer', '10'::jsonb, '9 + 1 = 10.', '9-ды 10-ға толықтыр.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Жылдам есептеу' and tp.grade = 1 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жылдам есепте', '7 + 3 = ?', 0 from public.topics where title = 'Жылдам есептеу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '7 + 3 = ?', 'short_answer', '10'::jsonb, '7 + 3 = 10.', '7-ні 10-ға толықтыр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Жылдам есептеу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жылдам есепте', '8 + 2 = ?', 1 from public.topics where title = 'Жылдам есептеу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '8 + 2 = ?', 'short_answer', '10'::jsonb, '8 + 2 = 10.', '8-ді 10-ға толықтыр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Жылдам есептеу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Жылдам есепте', '6 + 4 = ?', 2 from public.topics where title = 'Жылдам есептеу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '6 + 4 = ?', 'multiple_choice', '"10"'::jsonb, '6 + 4 = 10.', '6-ны 10-ға толықтыр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Жылдам есептеу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('10', true, 0), ('9', false, 1), ('11', false, 2), ('8', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Жылдам есептеу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Теңдікті құра', '6-ны 10-ға толықтыратын теңдікті текшелерден құра.', jsonb_build_object('kind', 'expression_builder', 'tiles', jsonb_build_array('6', '4', '10', '+', '='), 'target', jsonb_build_array('6', '+', '4', '=', '10')), 3 from public.topics where title = 'Жылдам есептеу' and grade = 1 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '6-ны 10-ға толықтыратын теңдікті текшелерден құра.', 'expression_builder', '6 + 4 = 10'::jsonb, '6 + 4 = 10.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Жылдам есептеу' and t2.grade = 1 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Ондыққа толықтыратын жұптарды сәйкестендір', 'Қосындысы 10 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(7,3), jsonb_build_array(8,2), jsonb_build_array(9,1), jsonb_build_array(6,4))), 4 from public.topics where title = 'Жылдам есептеу' and grade = 1 and track = 'logic';

