-- Generated by scripts/generateLessonSeed.ts from src/data/lessonContent/grade4Logic.ts.
-- Do not hand-edit — change the content module and regenerate instead.
-- ==== Сан және цифр (4-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Санның жазылуындағы цифрлар мен санның өзінің айырмашылығын түсіну, көпразрядты санның разрядтық құрамын анықтау.' where title = 'Сан және цифр' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('437 саны үш цифрдан тұрады: 4, 3, 7. Сан — тұтас мән, ал цифр — сол санды жазуға қолданылатын белгі.', '437 = 400 + 30 + 7 — жүздіктер, ондықтар және бірліктер қосындысы.')), 0 from public.topics where title = 'Сан және цифр' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', '437 санының бірліктер разрядындағы жасырын цифрды тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('4', '3', '?'), 'blankIndex', 2, 'correctValue', '7'), 0 from public.topics where title = 'Сан және цифр' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Сан мен цифрдің айырмашылығы неде?', 0 from public.topics where title = 'Сан және цифр' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '826 санының жүздіктер разрядындағы цифрды тап.', '{}'::jsonb, 0 from public.topics where title = 'Сан және цифр' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '826 санының жүздіктер разрядындағы цифрды тап.', 'short_answer', '8'::jsonb, '826 санында 8 — жүздіктер, 2 — ондықтар, 6 — бірліктер.', 'Санды солдан оқы: бірінші цифр — жүздіктер.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Сан және цифр' and tp.grade = 4 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Разрядты тап', '345 санының ондықтар разрядындағы цифрды тап.', 0 from public.topics where title = 'Сан және цифр' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '345 санының ондықтар разрядындағы цифрды тап.', 'short_answer', '4'::jsonb, '345-те 3 — жүздіктер, 4 — ондықтар, 5 — бірліктер.', 'Ортаңғы цифр — ондықтар.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сан және цифр' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Разрядты тап', '702 санының бірліктер разрядындағы цифрды тап.', 1 from public.topics where title = 'Сан және цифр' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '702 санының бірліктер разрядындағы цифрды тап.', 'short_answer', '2'::jsonb, '702-де соңғы цифр — бірліктер.', 'Санның соңғы цифрі.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сан және цифр' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Разрядты тап', '918 санының жүздіктер разрядындағы цифрды тап.', 2 from public.topics where title = 'Сан және цифр' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '918 санының жүздіктер разрядындағы цифрды тап.', 'multiple_choice', '"9"'::jsonb, '918-де бірінші цифр 9 — жүздіктер.', 'Санның бірінші цифрі.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Сан және цифр' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('9', true, 0), ('1', false, 1), ('8', false, 2), ('0', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Сан және цифр' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'ordering', 'Өсу ретімен тіз', 'Сандарды жүздіктер разряды бойынша өсу ретімен тіз.', jsonb_build_object('items', jsonb_build_array('345', '702', '918')), 3 from public.topics where title = 'Сан және цифр' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Санды жүздігімен сәйкестендір', 'Санды оның жүздіктер разрядының мәнімен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(345,300), jsonb_build_array(702,700), jsonb_build_array(918,900), jsonb_build_array(456,400))), 4 from public.topics where title = 'Сан және цифр' and grade = 4 and track = 'logic';


-- ==== Арифметикалық тепе-теңдіктер (4-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Теңдіктің екі жағының өзара тең болу шартын түсініп, жетіспейтін мәнді табу.' where title = 'Арифметикалық тепе-теңдіктер' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('9 + 6 = 8 + ? теңдігінде екі жақ өзара тең болуы керек.', '9 + 6 = 15, сондықтан 8 + ? = 15, демек ? = 7.')), 0 from public.topics where title = 'Арифметикалық тепе-теңдіктер' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Теңдіктің екі жағы тең болуы үшін жасырын санды тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('9', '+', '6', '=', '8', '+', '?'), 'blankIndex', 6, 'correctValue', '7'), 0 from public.topics where title = 'Арифметикалық тепе-теңдіктер' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Теңдіктің екі жағы тең болу үшін не істеу керек?', 0 from public.topics where title = 'Арифметикалық тепе-теңдіктер' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '12 + 5 = 9 + ?. Жасырын сан нешеге тең?', '{}'::jsonb, 0 from public.topics where title = 'Арифметикалық тепе-теңдіктер' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '12 + 5 = 9 + ?. Жасырын сан нешеге тең?', 'short_answer', '8'::jsonb, '12 + 5 = 17, ал 9 + 8 = 17.', 'Сол жақтың қосындысын тап та, оң жақпен теңестір.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Арифметикалық тепе-теңдіктер' and tp.grade = 4 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Теңдікті теңестір', '14 + 8 = 15 + ?. Жасырын сан нешеге тең?', 0 from public.topics where title = 'Арифметикалық тепе-теңдіктер' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '14 + 8 = 15 + ?. Жасырын сан нешеге тең?', 'short_answer', '7'::jsonb, '14 + 8 = 22, 22 − 15 = 7.', 'Сол жақтың қосындысын тап.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Арифметикалық тепе-теңдіктер' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Теңдікті теңестір', '20 − 6 = ? + 5. Жасырын сан нешеге тең?', 1 from public.topics where title = 'Арифметикалық тепе-теңдіктер' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '20 − 6 = ? + 5. Жасырын сан нешеге тең?', 'short_answer', '9'::jsonb, '20 − 6 = 14, 14 − 5 = 9.', 'Сол жақтың нәтижесін тап.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Арифметикалық тепе-теңдіктер' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Теңдікті теңестір', '7 × 3 = ? + 11. Жасырын сан нешеге тең?', 2 from public.topics where title = 'Арифметикалық тепе-теңдіктер' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '7 × 3 = ? + 11. Жасырын сан нешеге тең?', 'multiple_choice', '"10"'::jsonb, '7 × 3 = 21, 21 − 11 = 10.', 'Сол жақтың нәтижесін тап.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Арифметикалық тепе-теңдіктер' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('10', true, 0), ('9', false, 1), ('11', false, 2), ('12', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Арифметикалық тепе-теңдіктер' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Теңдікті құрастыр', '14 + 8 = 15 + ? теңдігін тексеретін теңдікті құрастыр.', jsonb_build_object('kind', 'expression_builder', 'tiles', jsonb_build_array('15', '+', '7', '=', '22', '6', '8'), 'target', jsonb_build_array('15', '+', '7', '=', '22')), 3 from public.topics where title = 'Арифметикалық тепе-теңдіктер' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '14 + 8 = 15 + ? теңдігін тексеретін теңдікті құрастыр.', 'expression_builder', to_jsonb('15 + 7 = 22'::text), '14 + 8 = 22, 15 + 7 = 22.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Арифметикалық тепе-теңдіктер' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Теңдікті сәйкестендір', 'Санды сол санның 8-ге қосындысымен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(7,15), jsonb_build_array(6,14), jsonb_build_array(9,17), jsonb_build_array(5,13))), 4 from public.topics where title = 'Арифметикалық тепе-теңдіктер' and grade = 4 and track = 'logic';


-- ==== Логикалық амалдар (4-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Заттар немесе сандар жиынын шарт бойынша салыстырып, логикалық қорытынды жасау.' where title = 'Логикалық амалдар' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('1-ден 10-ға дейінгі сандардың ішінде жұп сандар: 2, 4, 6, 8, 10 — барлығы 5.', '3-ке бөлінетін сандар: 3, 6, 9 — барлығы 3. 5 > 3, демек жұп сандар көп.')), 0 from public.topics where title = 'Логикалық амалдар' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Қайсысы көп екенін салыстыр.', jsonb_build_object('kind', 'value-compare', 'labelA', 'Жұп сандар саны', 'labelB', '3-ке бөлінетін сандар саны', 'numericA', 5, 'numericB', 3), 0 from public.topics where title = 'Логикалық амалдар' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Логикалық қорытынды жасау үшін алдымен нені санау керек?', 0 from public.topics where title = 'Логикалық амалдар' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '1-ден 20-ға дейінгі тақ сандар 10, ал 5-ке бөлінетін сандар 4. Тақ сандар неше санға көп?', '{}'::jsonb, 0 from public.topics where title = 'Логикалық амалдар' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '1-ден 20-ға дейінгі тақ сандар 10, ал 5-ке бөлінетін сандар 4. Тақ сандар неше санға көп?', 'short_answer', '6'::jsonb, '10 − 4 = 6.', 'Екі санның айырмасын тап.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Логикалық амалдар' and tp.grade = 4 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Логикалық қорытынды', '1-ден 15-ке дейінгі жұп сандар саны 7, ал 3-ке бөлінетін сандар саны 5. Жұп сандар неше санға көп?', 0 from public.topics where title = 'Логикалық амалдар' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '1-ден 15-ке дейінгі жұп сандар саны 7, ал 3-ке бөлінетін сандар саны 5. Жұп сандар неше санға көп?', 'short_answer', '2'::jsonb, '7 − 5 = 2.', 'Екі санды салыстыр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Логикалық амалдар' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Логикалық қорытынды', '1-ден 10-ға дейінгі тақ сандар саны мен жұп сандар санының қосындысын тап.', 1 from public.topics where title = 'Логикалық амалдар' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '1-ден 10-ға дейінгі тақ сандар саны мен жұп сандар санының қосындысын тап.', 'short_answer', '10'::jsonb, 'Тақ сандар — 5, жұп сандар — 5, қосындысы 10.', 'Екі санды қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Логикалық амалдар' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Логикалық қорытынды', '1-ден 12-ге дейінгі 4-ке бөлінетін сандар саны нешеу?', 2 from public.topics where title = 'Логикалық амалдар' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '1-ден 12-ге дейінгі 4-ке бөлінетін сандар саны нешеу?', 'multiple_choice', '"3"'::jsonb, '4, 8, 12 — барлығы 3 сан.', '4, 8, 12-ні санап шық.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Логикалық амалдар' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('3', true, 0), ('4', false, 1), ('2', false, 2), ('5', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Логикалық амалдар' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'drag_drop', 'Сандарды ажырат', 'Әр санды дұрыс топқа орналастыр.', jsonb_build_object('items', jsonb_build_array(jsonb_build_object('label', '4', 'group', 'a'), jsonb_build_object('label', '9', 'group', 'b'), jsonb_build_object('label', '8', 'group', 'a'), jsonb_build_object('label', '3', 'group', 'b')), 'groupALabel', 'Жұп сан', 'groupBLabel', '3-ке бөлінеді'), 3 from public.topics where title = 'Логикалық амалдар' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 12 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(4,8), jsonb_build_array(9,3), jsonb_build_array(5,7), jsonb_build_array(6,6))), 4 from public.topics where title = 'Логикалық амалдар' and grade = 4 and track = 'logic';


-- ==== Қарапайым периодтық есептер (4-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Периодты түрде қайталанатын тізбекте белгілі бір реттегі элементті табу.' where title = 'Қарапайым периодтық есептер' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Түстер 3 периодпен қайталанады: қызыл, көк, жасыл, қызыл, көк, жасыл...', 'Кез келген орынды период ұзындығына бөліп, қалдық арқылы сол орындағы элементті табамыз.')), 0 from public.topics where title = 'Қарапайым периодтық есептер' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Түстер тізбегіндегі заңдылықты тауып, жасырын түсті тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('қызыл', 'көк', 'жасыл', 'қызыл', '?'), 'blankIndex', 4, 'correctValue', 'көк'), 0 from public.topics where title = 'Қарапайым периодтық есептер' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Периодтық тізбекте керекті орынды табу үшін нені білу керек (период ұзындығын)?', 0 from public.topics where title = 'Қарапайым периодтық есептер' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Сандар 3 периодпен қайталанады: 2, 5, 9, 2, 5, 9... 8-ші орында қандай сан тұр?', '{}'::jsonb, 0 from public.topics where title = 'Қарапайым периодтық есептер' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Сандар 3 периодпен қайталанады: 2, 5, 9, 2, 5, 9... 8-ші орында қандай сан тұр?', 'short_answer', '5'::jsonb, '8 ÷ 3 = 2 қалдық 2, демек период ішіндегі 2-ші сан — 5.', 'Орын нөмірін период ұзындығына бөл, қалдықты тап.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Қарапайым периодтық есептер' and tp.grade = 4 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Периодты тап', 'Сандар 4 периодпен қайталанады: 2, 5, 9, 1, 2, 5, 9, 1... 10-шы орында қандай сан тұр?', 0 from public.topics where title = 'Қарапайым периодтық есептер' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Сандар 4 периодпен қайталанады: 2, 5, 9, 1, 2, 5, 9, 1... 10-шы орында қандай сан тұр?', 'short_answer', '5'::jsonb, '10 ÷ 4 = 2 қалдық 2, демек 2-ші сан — 5.', 'Қалдықты тап.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қарапайым периодтық есептер' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Периодты тап', 'Заттар 5 периодпен қайталанады. 23-ші орын период ішінде нешінші орынға сәйкес келеді?', 1 from public.topics where title = 'Қарапайым периодтық есептер' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Заттар 5 периодпен қайталанады. 23-ші орын период ішінде нешінші орынға сәйкес келеді?', 'short_answer', '3'::jsonb, '23 ÷ 5 = 4 қалдық 3, демек 3-ші орын.', 'Қалдықты тап.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қарапайым периодтық есептер' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Периодты тап', 'Апта күндері 7-ден қайталанады. Бүгін сейсенбі болса, 14 күннен кейін қандай күн болады?', 2 from public.topics where title = 'Қарапайым периодтық есептер' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Апта күндері 7-ден қайталанады. Бүгін сейсенбі болса, 14 күннен кейін қандай күн болады?', 'multiple_choice', '"сейсенбі"'::jsonb, '14 ÷ 7 = 2 қалдық 0, демек дәл сол күн қайталанады.', '14-ті 7-ге қалдықсыз бөлуге бола ма?', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қарапайым периодтық есептер' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('сейсенбі', true, 0), ('дүйсенбі', false, 1), ('сәрсенбі', false, 2), ('бейсенбі', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Қарапайым периодтық есептер' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', 'Бүгін сейсенбі. 14 күннен кейін қандай күн болатынын тексер.', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('14 ÷ 7 = 2 қалдық 0', 'Демек дүйсенбі болады'), 'errorIndex', 1), 3 from public.topics where title = 'Қарапайым периодтық есептер' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Бүгін сейсенбі. 14 күннен кейін қандай күн болатынын тексер.', 'find_error', '1'::jsonb, 'Қалдық 0 болса, дәл сол күн қайталанады — сейсенбі, дүйсенбі емес.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қарапайым периодтық есептер' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Периодты сәйкестендір', 'Санды 3-ке бөлгендегі қалдығымен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(7,1), jsonb_build_array(8,2), jsonb_build_array(9,0), jsonb_build_array(10,1))), 4 from public.topics where title = 'Қарапайым периодтық есептер' and grade = 4 and track = 'logic';


-- ==== Жою тәсілі (4-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Екі белгісізі бар қарапайым есептерді "жою" (біреуін алып тастау) тәсілімен шешу.' where title = 'Жою тәсілі' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('2 алма + 3 алмұрт = 16, 2 алма + 1 алмұрт = 8 болса...', 'Екі теңдікті бір-бірінен азайтсақ, алмалар "жойылады": 3 алмұрт − 1 алмұрт = 16 − 8, яғни 2 алмұрт = 8, бір алмұрт = 4.')), 0 from public.topics where title = 'Жою тәсілі' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', null, jsonb_build_object('total', 16, 'startLeft', 8), 0 from public.topics where title = 'Жою тәсілі' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Жою тәсілінде неліктен екі теңдікті бір-бірінен азайтамыз?', 0 from public.topics where title = 'Жою тәсілі' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '3 қалам + 2 дәптер = 19, 3 қалам + 1 дәптер = 14. Бір дәптердің бағасын тап.', '{}'::jsonb, 0 from public.topics where title = 'Жою тәсілі' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3 қалам + 2 дәптер = 19, 3 қалам + 1 дәптер = 14. Бір дәптердің бағасын тап.', 'short_answer', '5'::jsonb, '19 − 14 = 5 — бір дәптердің бағасы.', 'Екі теңдікті бір-бірінен азайт.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Жою тәсілі' and tp.grade = 4 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жойып тап', '4 алма + 2 алмұрт = 22, 4 алма + 1 алмұрт = 14. Бір алмұрттың бағасын тап.', 0 from public.topics where title = 'Жою тәсілі' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '4 алма + 2 алмұрт = 22, 4 алма + 1 алмұрт = 14. Бір алмұрттың бағасын тап.', 'short_answer', '8'::jsonb, '22 − 14 = 8.', 'Екі теңдікті азайт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Жою тәсілі' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жойып тап', '5 қарындаш + 3 қалам = 29, 5 қарындаш + 1 қалам = 17. Бір қаламның бағасын тап.', 1 from public.topics where title = 'Жою тәсілі' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5 қарындаш + 3 қалам = 29, 5 қарындаш + 1 қалам = 17. Бір қаламның бағасын тап.', 'short_answer', '6'::jsonb, '(29 − 17) ÷ 2 = 6.', 'Айырманы тауып, 2-ге бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Жою тәсілі' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Жойып тап', '2 кітап + 4 дәптер = 26, 2 кітап + 2 дәптер = 16. Бір дәптердің бағасы нешеге тең?', 2 from public.topics where title = 'Жою тәсілі' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '2 кітап + 4 дәптер = 26, 2 кітап + 2 дәптер = 16. Бір дәптердің бағасы нешеге тең?', 'multiple_choice', '"5"'::jsonb, '(26 − 16) ÷ 2 = 5.', 'Айырманы тауып, 2-ге бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Жою тәсілі' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('5', true, 0), ('4', false, 1), ('6', false, 2), ('3', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Жою тәсілі' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Жою қадамын құрастыр', '4 алма + 2 алмұрт = 22, 4 алма + 1 алмұрт = 14. Алмұрттың бағасын табу өрнегін құрастыр.', jsonb_build_object('kind', 'expression_builder', 'tiles', jsonb_build_array('22', '−', '14', '=', '8', '6', '10'), 'target', jsonb_build_array('22', '−', '14', '=', '8')), 3 from public.topics where title = 'Жою тәсілі' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '4 алма + 2 алмұрт = 22, 4 алма + 1 алмұрт = 14. Алмұрттың бағасын табу өрнегін құрастыр.', 'expression_builder', to_jsonb('22 − 14 = 8'::text), '22 − 14 = 8.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Жою тәсілі' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 22 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(14,8), jsonb_build_array(9,13), jsonb_build_array(19,3), jsonb_build_array(4,18))), 4 from public.topics where title = 'Жою тәсілі' and grade = 4 and track = 'logic';


-- ==== Аудан (4-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Тіктөртбұрыш пен шаршының ауданын есептеп, ауданы мен бір қабырғасы бойынша екінші қабырғасын табу.' where title = 'Аудан' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Ауданы белгілі тіктөртбұрыштың бір қабырғасын біле отырып, екінші қабырғасын табуға болады.', 'Ені 6 м, ауданы 48 шаршы м болса, ұзындығы 48 ÷ 6 = 8 м.')), 0 from public.topics where title = 'Аудан' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Тіктөртбұрыштың ауданын тап.', jsonb_build_object('kind', 'area', 'width', 6, 'height', 4, 'unit', 'м'), 0 from public.topics where title = 'Аудан' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Ауданы және ені белгілі болса, ұзындықты қалай табамыз?', 0 from public.topics where title = 'Аудан' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Ауданы 54 шаршы см, ені 6 см тіктөртбұрыштың ұзындығын тап.', '{}'::jsonb, 0 from public.topics where title = 'Аудан' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Ауданы 54 шаршы см, ені 6 см тіктөртбұрыштың ұзындығын тап.', 'short_answer', '9'::jsonb, '54 ÷ 6 = 9 см.', 'Ауданды еніне бөл.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Аудан' and tp.grade = 4 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Қабырғасын тап', 'Ауданы 63 шаршы м, ұзындығы 9 м жердің енін тап.', 0 from public.topics where title = 'Аудан' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Ауданы 63 шаршы м, ұзындығы 9 м жердің енін тап.', 'short_answer', '7'::jsonb, '63 ÷ 9 = 7 м.', 'Ауданды ұзындығына бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Аудан' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Ауданын тап', 'Қабырғасы 9 см шаршының ауданы нешеге тең?', 1 from public.topics where title = 'Аудан' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Қабырғасы 9 см шаршының ауданы нешеге тең?', 'short_answer', '81'::jsonb, '9 × 9 = 81 шаршы см.', 'Қабырғаны өзіне көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Аудан' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Қабырғасын тап', 'Ені 7 см, ауданы 56 шаршы см тіктөртбұрыштың ұзындығы нешеге тең?', 2 from public.topics where title = 'Аудан' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Ені 7 см, ауданы 56 шаршы см тіктөртбұрыштың ұзындығы нешеге тең?', 'multiple_choice', '"8"'::jsonb, '56 ÷ 7 = 8 см.', 'Ауданды еніне бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Аудан' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('8', true, 0), ('7', false, 1), ('9', false, 2), ('6', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Аудан' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Енін өлш', 'Тіктөртбұрыштың енін сызғышпен өлш.', jsonb_build_object('kind', 'measurement', 'unit', 'см', 'length', 9, 'maxScale', 12), 3 from public.topics where title = 'Аудан' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Тіктөртбұрыштың енін сызғышпен өлш.', 'measurement', '9'::jsonb, 'Сызғыш бойынша ені 9 см.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Аудан' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Ауданды сәйкестендір', 'Шаршының қабырғасын оның ауданымен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(6,36), jsonb_build_array(7,49), jsonb_build_array(8,64), jsonb_build_array(9,81))), 4 from public.topics where title = 'Аудан' and grade = 4 and track = 'logic';


-- ==== Қозғалысқа берілген есептер (4-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Жылдамдық, уақыт және қашықтық арасындағы байланысты (қашықтық = жылдамдық × уақыт) есептерде қолдану.' where title = 'Қозғалысқа берілген есептер' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'video', null, 'https://youtube.com/shorts/yaA58Am1-Yo?feature=shared', jsonb_build_object('kind', 'video', 'caption', 'Қашықтық = жылдамдық × уақыт. Көлік сағатына 60 км жылдамдықпен 2 сағат жүрсе, 60 × 2 = 120 км жол жүреді.'), 0 from public.topics where title = 'Қозғалысқа берілген есептер' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Бірінші көліктің жылдамдығы 6, екіншісінікі 9. Қайсысы жылдам?', jsonb_build_object('kind', 'compare', 'iconA', 'cube', 'countA', 6, 'iconB', 'cube', 'countB', 9), 0 from public.topics where title = 'Қозғалысқа берілген есептер' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Қашықтықты табу үшін қандай екі шаманы білу керек?', 0 from public.topics where title = 'Қозғалысқа берілген есептер' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Пойыз сағатына 75 км жылдамдықпен 3 сағат жүрді. Қанша қашықтыққа жетті?', '{}'::jsonb, 0 from public.topics where title = 'Қозғалысқа берілген есептер' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Пойыз сағатына 75 км жылдамдықпен 3 сағат жүрді. Қанша қашықтыққа жетті?', 'short_answer', '225'::jsonb, '75 × 3 = 225 км.', 'Жылдамдықты уақытқа көбейт.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Қозғалысқа берілген есептер' and tp.grade = 4 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Қашықтықты тап', 'Велосипедші сағатына 15 км жылдамдықпен 4 сағат жүрді. Қанша қашықтыққа жетті?', 0 from public.topics where title = 'Қозғалысқа берілген есептер' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Велосипедші сағатына 15 км жылдамдықпен 4 сағат жүрді. Қанша қашықтыққа жетті?', 'short_answer', '60'::jsonb, '15 × 4 = 60 км.', 'Жылдамдықты уақытқа көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қозғалысқа берілген есептер' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жылдамдықты тап', 'Көлік 240 км жолды 4 сағатта жүрді. Оның жылдамдығы нешеге тең?', 1 from public.topics where title = 'Қозғалысқа берілген есептер' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Көлік 240 км жолды 4 сағатта жүрді. Оның жылдамдығы нешеге тең?', 'short_answer', '60'::jsonb, '240 ÷ 4 = 60 км/сағ.', 'Қашықтықты уақытқа бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қозғалысқа берілген есептер' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Қашықтықты тап', 'Ұшақ сағатына 500 км жылдамдықпен 3 сағат ұшты. Қанша қашықтыққа жетті?', 2 from public.topics where title = 'Қозғалысқа берілген есептер' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Ұшақ сағатына 500 км жылдамдықпен 3 сағат ұшты. Қанша қашықтыққа жетті?', 'multiple_choice', '"1500"'::jsonb, '500 × 3 = 1500 км.', 'Жылдамдықты уақытқа көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қозғалысқа берілген есептер' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('1500', true, 0), ('1000', false, 1), ('2000', false, 2), ('1200', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Қозғалысқа берілген есептер' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'ordering', 'Өсу ретімен тіз', 'Нәтижелерді өсу ретімен тіз: 15 × 4, 75 × 3, 500 × 3.', jsonb_build_object('items', jsonb_build_array('60', '225', '1500')), 3 from public.topics where title = 'Қозғалысқа берілген есептер' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Уақыт пен қашықтықты сәйкестендір', 'Жылдамдығы 75 км/сағ болғанда, уақытты сол уақытта жүрген қашықтықпен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(1,75), jsonb_build_array(2,150), jsonb_build_array(3,225), jsonb_build_array(4,300))), 4 from public.topics where title = 'Қозғалысқа берілген есептер' and grade = 4 and track = 'logic';


-- ==== Тепе-теңдік есептері (4-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Таразы теңгерімі арқылы белгісіз салмақты табу немесе екі жақтың теңдігін тексеру.' where title = 'Тепе-теңдік есептері' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Таразының екі басы тең болса, екі жақтағы заттардың салмағы тең.', 'Егер бір жақ ауыр болса, теңгерім үшін жеңіл жаққа зат қосу немесе ауыр жақтан зат алу керек.')), 0 from public.topics where title = 'Тепе-теңдік есептері' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Таразының екі жағында 6-дан алма тұр. Таразы теңгерімде ме?', jsonb_build_object('kind', 'compare', 'iconA', 'apple', 'countA', 6, 'iconB', 'apple', 'countB', 6), 0 from public.topics where title = 'Тепе-теңдік есептері' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Таразы теңгерімде болу үшін не керек?', 0 from public.topics where title = 'Тепе-теңдік есептері' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Таразының бір жағында 24 кг, екінші жағында 18 кг жүк бар. Теңгерім үшін екінші жаққа қанша кг қосу керек?', '{}'::jsonb, 0 from public.topics where title = 'Тепе-теңдік есептері' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Таразының бір жағында 24 кг, екінші жағында 18 кг жүк бар. Теңгерім үшін екінші жаққа қанша кг қосу керек?', 'short_answer', '6'::jsonb, '24 − 18 = 6 кг.', 'Ауыр жақтан жеңіл жақты азайт.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Тепе-теңдік есептері' and tp.grade = 4 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Теңгерімге келтір', 'Бір жағында 15 кг, екінші жағында 9 кг жүк бар. Теңгерім үшін екінші жаққа қанша кг қосу керек?', 0 from public.topics where title = 'Тепе-теңдік есептері' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Бір жағында 15 кг, екінші жағында 9 кг жүк бар. Теңгерім үшін екінші жаққа қанша кг қосу керек?', 'short_answer', '6'::jsonb, '15 − 9 = 6 кг.', 'Ауыр жақтан жеңіл жақты азайт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Тепе-теңдік есептері' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Теңгерімге келтір', 'Таразының екі жағы тең болу үшін әр жақта 20 кг болу керек. Бір жағында 12 кг тұр. Қанша кг жетіспейді?', 1 from public.topics where title = 'Тепе-теңдік есептері' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Таразының екі жағы тең болу үшін әр жақта 20 кг болу керек. Бір жағында 12 кг тұр. Қанша кг жетіспейді?', 'short_answer', '8'::jsonb, '20 − 12 = 8 кг.', 'Керектіден барды азайт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Тепе-теңдік есептері' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Теңгерімге келтір', 'Бір жағында 30 кг, екінші жағында 24 кг жүк бар. Теңгерім үшін ауыр жақтан қанша кг алу керек?', 2 from public.topics where title = 'Тепе-теңдік есептері' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Бір жағында 30 кг, екінші жағында 24 кг жүк бар. Теңгерім үшін ауыр жақтан қанша кг алу керек?', 'multiple_choice', '"6"'::jsonb, '30 − 24 = 6 кг.', 'Ауыр жақтан жеңіл жақты азайт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Тепе-теңдік есептері' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('6', true, 0), ('5', false, 1), ('7', false, 2), ('4', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Тепе-теңдік есептері' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', 'Таразыны тексер: бір жағында 30 кг, екінші жағында 24 кг. Ауыр жақтан неше кг алу керек?', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('Ауыр мен жеңіл жақтың айырмасын табамыз', '30 − 24 = 5'), 'errorIndex', 1), 3 from public.topics where title = 'Тепе-теңдік есептері' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Таразыны тексер: бір жағында 30 кг, екінші жағында 24 кг. Ауыр жақтан неше кг алу керек?', 'find_error', '1'::jsonb, '30 − 24 = 6, 5 емес.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Тепе-теңдік есептері' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 30 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(12,18), jsonb_build_array(9,21), jsonb_build_array(24,6), jsonb_build_array(15,15))), 4 from public.topics where title = 'Тепе-теңдік есептері' and grade = 4 and track = 'logic';


-- ==== Комбинаторика (4-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Үш немесе одан да көп таңдау тобы болғанда, барлық мүмкін нұсқаларды көбейту арқылы санау.' where title = 'Комбинаторика' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('3 түрлі көйлек, 2 түрлі белдік, 2 түрлі аяқ киім болса...', 'Барлық нұсқа саны: 3 × 2 × 2 = 12.')), 0 from public.topics where title = 'Комбинаторика' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', '3 көйлек, 2 белдік, 2 аяқ киімнен жасалатын барлық нұсқаны санап шық.', jsonb_build_object('kind', 'count-click', 'icon', 'star', 'count', 12), 0 from public.topics where title = 'Комбинаторика' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Үш түрлі таңдау болғанда жалпы нұсқа санын қалай табамыз (қосамыз ба, көбейтеміз бе)?', 0 from public.topics where title = 'Комбинаторика' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '4 түрлі қалам мен 3 түрлі дәптерден неше комбинация жасауға болады?', '{}'::jsonb, 0 from public.topics where title = 'Комбинаторика' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '4 түрлі қалам мен 3 түрлі дәптерден неше комбинация жасауға болады?', 'short_answer', '12'::jsonb, '4 × 3 = 12.', 'Екі санды көбейт.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Комбинаторика' and tp.grade = 4 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Комбинацияны сана', '2 шляпа, 3 шарф, 2 қолғаптан неше комбинация жасауға болады?', 0 from public.topics where title = 'Комбинаторика' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '2 шляпа, 3 шарф, 2 қолғаптан неше комбинация жасауға болады?', 'short_answer', '12'::jsonb, '2 × 3 × 2 = 12.', 'Үш санды көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Комбинаторика' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Комбинацияны сана', '5 түрлі жеміс пен 2 түрлі стаканнан неше таңдау жасауға болады?', 1 from public.topics where title = 'Комбинаторика' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5 түрлі жеміс пен 2 түрлі стаканнан неше таңдау жасауға болады?', 'short_answer', '10'::jsonb, '5 × 2 = 10.', 'Екі санды көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Комбинаторика' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Комбинацияны сана', '3 түс пен 4 өлшемнен неше киім түрін жасауға болады?', 2 from public.topics where title = 'Комбинаторика' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3 түс пен 4 өлшемнен неше киім түрін жасауға болады?', 'multiple_choice', '"12"'::jsonb, '3 × 4 = 12.', 'Екі санды көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Комбинаторика' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('12', true, 0), ('7', false, 1), ('10', false, 2), ('14', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Комбинаторика' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Комбинацияны құрастыр', '2 шляпа, 3 шарф, 2 қолғаптан комбинация санын табу өрнегін құрастыр.', jsonb_build_object('kind', 'expression_builder', 'tiles', jsonb_build_array('2', '×', '3', '×', '2', '=', '12', '10', '8'), 'target', jsonb_build_array('2', '×', '3', '×', '2', '=', '12')), 3 from public.topics where title = 'Комбинаторика' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '2 шляпа, 3 шарф, 2 қолғаптан комбинация санын табу өрнегін құрастыр.', 'expression_builder', to_jsonb('2 × 3 × 2 = 12'::text), '2 × 3 × 2 = 12.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Комбинаторика' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Көбейтіндіні сәйкестендір', 'Санды оның 5-ке көбейтіндісімен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(2,10), jsonb_build_array(3,15), jsonb_build_array(4,20), jsonb_build_array(6,30))), 4 from public.topics where title = 'Комбинаторика' and grade = 4 and track = 'logic';


-- ==== Тиімді тәсіл: көбейту және бөлу (4-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Көбейту мен бөлуді санды ондықтар мен бірліктерге жіктеу арқылы тиімді орындау.' where title = 'Тиімді тәсіл: көбейту және бөлу' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('23 × 4 есептегенде 23-ті 20 мен 3-ке бөліп көбейтеміз: 20 × 4 = 80, 3 × 4 = 12, 80 + 12 = 92.', 'Бұл тәсіл үлкен сандарды көбейткенде ойша есептеуді жеңілдетеді.')), 0 from public.topics where title = 'Тиімді тәсіл: көбейту және бөлу' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', null, jsonb_build_object('total', 20, 'startLeft', 17), 0 from public.topics where title = 'Тиімді тәсіл: көбейту және бөлу' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Көбейтуді тиімді орындау үшін санды қалай бөлеміз (ондықтар мен бірліктерге)?', 0 from public.topics where title = 'Тиімді тәсіл: көбейту және бөлу' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Тиімді тәсілмен есепте: 34 × 3', '{}'::jsonb, 0 from public.topics where title = 'Тиімді тәсіл: көбейту және бөлу' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Тиімді тәсілмен есепте: 34 × 3', 'short_answer', '102'::jsonb, '34 × 3 = 30×3 + 4×3 = 90 + 12 = 102.', '34-ті 30 мен 4-ке бөл.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Тиімді тәсіл: көбейту және бөлу' and tp.grade = 4 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Тиімді көбейт', '46 × 2 неше?', 0 from public.topics where title = 'Тиімді тәсіл: көбейту және бөлу' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '46 × 2 неше?', 'short_answer', '92'::jsonb, '40×2 + 6×2 = 80 + 12 = 92.', '46-ны 40 мен 6-ға бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Тиімді тәсіл: көбейту және бөлу' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Тиімді бөл', '96 ÷ 4 неше?', 1 from public.topics where title = 'Тиімді тәсіл: көбейту және бөлу' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '96 ÷ 4 неше?', 'short_answer', '24'::jsonb, '80÷4 + 16÷4 = 20 + 4 = 24.', '96-ны 80 мен 16-ға бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Тиімді тәсіл: көбейту және бөлу' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Тиімді көбейт', '28 × 3 нешеге тең?', 2 from public.topics where title = 'Тиімді тәсіл: көбейту және бөлу' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '28 × 3 нешеге тең?', 'multiple_choice', '"84"'::jsonb, '20×3 + 8×3 = 60 + 24 = 84.', '28-ді 20 мен 8-ге бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Тиімді тәсіл: көбейту және бөлу' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('84', true, 0), ('74', false, 1), ('94', false, 2), ('64', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Тиімді тәсіл: көбейту және бөлу' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'ordering', 'Өсу ретімен тіз', 'Нәтижелерді өсу ретімен тіз: 46 × 2, 96 ÷ 4, 28 × 3.', jsonb_build_object('items', jsonb_build_array('24', '84', '92')), 3 from public.topics where title = 'Тиімді тәсіл: көбейту және бөлу' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Санды екі еселігімен сәйкестендір', 'Санды оның екі еселігімен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(12,24), jsonb_build_array(15,30), jsonb_build_array(18,36), jsonb_build_array(21,42))), 4 from public.topics where title = 'Тиімді тәсіл: көбейту және бөлу' and grade = 4 and track = 'logic';


-- ==== Артық қалу және жетпей қалу мәселесі (4-сынып, logic) ====
update public.topics set status = 'published', learning_objective = 'Артық қалу және жетпей қалу мәліметтері бойынша заттар мен адамдар санын табу тәсілін меңгеру.' where title = 'Артық қалу және жетпей қалу мәселесі' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Балаларға 3-тен алма берсе, 4 алма артық қалады; 4-тен берсе, 2 алма жетпейді.', 'Артық пен жетпеушілікті қосып, бір балаға берілетін сан айырмасына бөлсек, балалар санын табамыз: (4 + 2) ÷ (4 − 3) = 6 бала.')), 0 from public.topics where title = 'Артық қалу және жетпей қалу мәселесі' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', null, jsonb_build_object('total', 6, 'startLeft', 4), 0 from public.topics where title = 'Артық қалу және жетпей қалу мәселесі' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Артық пен жетпей қалу мәселесінде балалар санын табу үшін не істейміз?', 0 from public.topics where title = 'Артық қалу және жетпей қалу мәселесі' and grade = 4 and track = 'logic';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Балаларға 2-ден кәмпит берсе, 5 кәмпит артық қалады; 3-тен берсе, 1 кәмпит жетпейді. Балалар саны нешеу?', '{}'::jsonb, 0 from public.topics where title = 'Артық қалу және жетпей қалу мәселесі' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Балаларға 2-ден кәмпит берсе, 5 кәмпит артық қалады; 3-тен берсе, 1 кәмпит жетпейді. Балалар саны нешеу?', 'short_answer', '6'::jsonb, '(5 + 1) ÷ (3 − 2) = 6.', 'Артық пен жетпейтінді қосып, айырымға бөл.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Артық қалу және жетпей қалу мәселесі' and tp.grade = 4 and tp.track = 'logic' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Балалар санын тап', 'Балаларға 4-тен дәптер берсе, 3 дәптер артық қалады; 5-тен берсе, 2 дәптер жетпейді. Балалар саны нешеу?', 0 from public.topics where title = 'Артық қалу және жетпей қалу мәселесі' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Балаларға 4-тен дәптер берсе, 3 дәптер артық қалады; 5-тен берсе, 2 дәптер жетпейді. Балалар саны нешеу?', 'short_answer', '5'::jsonb, '(3 + 2) ÷ (5 − 4) = 5.', 'Артық пен жетпейтінді қосып, айырымға бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Артық қалу және жетпей қалу мәселесі' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Балалар санын тап', 'Балаларға 6-дан алма берсе, 3 алма артық қалады; 7-ден берсе, 4 алма жетпейді. Балалар саны нешеу?', 1 from public.topics where title = 'Артық қалу және жетпей қалу мәселесі' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Балаларға 6-дан алма берсе, 3 алма артық қалады; 7-ден берсе, 4 алма жетпейді. Балалар саны нешеу?', 'short_answer', '7'::jsonb, '(3 + 4) ÷ (7 − 6) = 7.', 'Артық пен жетпейтінді қосып, айырымға бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Артық қалу және жетпей қалу мәселесі' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Балалар санын тап', 'Балаларға 3-тен қарындаш берсе, 5 қарындаш артық қалады; 5-тен берсе, 3 қарындаш жетпейді. Балалар саны нешеу?', 2 from public.topics where title = 'Артық қалу және жетпей қалу мәселесі' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Балаларға 3-тен қарындаш берсе, 5 қарындаш артық қалады; 5-тен берсе, 3 қарындаш жетпейді. Балалар саны нешеу?', 'multiple_choice', '"4"'::jsonb, '(5 + 3) ÷ (5 − 3) = 4.', 'Артық пен жетпейтінді қосып, айырымға бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Артық қалу және жетпей қалу мәселесі' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('4', true, 0), ('5', false, 1), ('6', false, 2), ('3', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Артық қалу және жетпей қалу мәселесі' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', 'Балалар санын тексер: 4-тен дәптер берсе 3 артық қалады, 5-тен берсе 2 жетпейді.', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('3 + 2 = 5', '5 ÷ (5 − 4) = 4'), 'errorIndex', 1), 3 from public.topics where title = 'Артық қалу және жетпей қалу мәселесі' and grade = 4 and track = 'logic';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Балалар санын тексер: 4-тен дәптер берсе 3 артық қалады, 5-тен берсе 2 жетпейді.', 'find_error', '1'::jsonb, '5 ÷ 1 = 5, 4 емес.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Артық қалу және жетпей қалу мәселесі' and t2.grade = 4 and t2.track = 'logic' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 9 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(5,4), jsonb_build_array(3,6), jsonb_build_array(7,2), jsonb_build_array(1,8))), 4 from public.topics where title = 'Артық қалу және жетпей қалу мәселесі' and grade = 4 and track = 'logic';

