-- Generated by scripts/generateLessonSeed.ts from src/data/lessonContent/grade2Base.ts.
-- Do not hand-edit — change the content module and regenerate instead.
-- ==== 100 көлеміндегі сандардың разрядтық құрамы (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = '100 көлеміндегі сандардың ондықтар мен бірліктерден тұратын разрядтық құрамын анықтау.' where title = '100 көлеміндегі сандардың разрядтық құрамы' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('68 саны 6 ондық пен 8 бірліктен тұрады: 68 = 60 + 8.', 'Кез келген екі таңбалы санды осылай ондықтар мен бірліктерге бөлуге болады.')), 0 from public.topics where title = '100 көлеміндегі сандардың разрядтық құрамы' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', null, jsonb_build_object('total', 18, 'startLeft', 10), 0 from public.topics where title = '100 көлеміндегі сандардың разрядтық құрамы' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Екі таңбалы санды разрядтарға бөлгенде нені табамыз?', 0 from public.topics where title = '100 көлеміндегі сандардың разрядтық құрамы' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '57 санының разрядтық құрамын анықта: неше ондық бар?', '{}'::jsonb, 0 from public.topics where title = '100 көлеміндегі сандардың разрядтық құрамы' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '57 санының разрядтық құрамын анықта: неше ондық бар?', 'short_answer', '5'::jsonb, '57 = 50 + 7, демек 5 ондық.', 'Санның бірінші цифрі — ондықтар саны.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = '100 көлеміндегі сандардың разрядтық құрамы' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Разрядын тап', '84 санында неше бірлік бар?', 0 from public.topics where title = '100 көлеміндегі сандардың разрядтық құрамы' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '84 санында неше бірлік бар?', 'short_answer', '4'::jsonb, '84 = 80 + 4, демек 4 бірлік.', 'Санның соңғы цифрі — бірліктер саны.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '100 көлеміндегі сандардың разрядтық құрамы' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Құрамын тап', '39 = 30 + ?. Жасырын санды тап.', 1 from public.topics where title = '100 көлеміндегі сандардың разрядтық құрамы' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '39 = 30 + ?. Жасырын санды тап.', 'short_answer', '9'::jsonb, '39 = 30 + 9.', '39-дан 30-ды азайт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '100 көлеміндегі сандардың разрядтық құрамы' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Разрядын тап', '76 санының ондықтар саны нешеу?', 2 from public.topics where title = '100 көлеміндегі сандардың разрядтық құрамы' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '76 санының ондықтар саны нешеу?', 'multiple_choice', '"7"'::jsonb, '76 = 70 + 6, демек 7 ондық.', 'Санның бірінші цифрі.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '100 көлеміндегі сандардың разрядтық құрамы' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('7', true, 0), ('6', false, 1), ('76', false, 2), ('10', false, 3)) as opt(text, is_correct, ord) where t2.title = '100 көлеміндегі сандардың разрядтық құрамы' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'ordering', 'Өсу ретімен тіз', 'Сандарды өсу ретімен тіз (кішіден үлкенге).', jsonb_build_object('items', jsonb_build_array('23', '45', '67', '89')), 3 from public.topics where title = '100 көлеміндегі сандардың разрядтық құрамы' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 100 болатын ондықтарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(30,70), jsonb_build_array(50,50), jsonb_build_array(90,10), jsonb_build_array(80,20))), 4 from public.topics where title = '100 көлеміндегі сандардың разрядтық құрамы' and grade = 2 and track = 'base';


-- ==== 1000 көлеміндегі сандарды оқу және жазу (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = '1000 көлеміндегі үш таңбалы сандарды дұрыс оқу және жазу.' where title = '1000 көлеміндегі сандарды оқу және жазу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('347 саны «үш жүз қырық жеті» деп оқылады: 3 жүздік, 4 ондық, 7 бірлік.', 'Санды жазғанда әрбір цифрдың орны (разряды) маңызды.')), 0 from public.topics where title = '1000 көлеміндегі сандарды оқу және жазу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', '347 санының бірліктер разрядындағы жасырын цифрды тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('3', '4', '?'), 'blankIndex', 2, 'correctValue', '7'), 0 from public.topics where title = '1000 көлеміндегі сандарды оқу және жазу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Үш таңбалы санда неше разряд бар (жүздік, ондық, бірлік)?', 0 from public.topics where title = '1000 көлеміндегі сандарды оқу және жазу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '526 санында неше жүздік бар?', '{}'::jsonb, 0 from public.topics where title = '1000 көлеміндегі сандарды оқу және жазу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '526 санында неше жүздік бар?', 'short_answer', '5'::jsonb, '526 санының бірінші цифрі 5 — жүздіктер саны.', 'Санның бірінші цифрін қара.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = '1000 көлеміндегі сандарды оқу және жазу' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Санмен жаз', '«Алты жүз он бес» санын цифрмен жаз (тек санмен).', 0 from public.topics where title = '1000 көлеміндегі сандарды оқу және жазу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '«Алты жүз он бес» санын цифрмен жаз (тек санмен).', 'short_answer', '615'::jsonb, 'Алты жүз он бес = 615.', 'Жүздік, ондық, бірлікті ретімен жаз.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '1000 көлеміндегі сандарды оқу және жазу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Разрядын тап', '203 санында неше ондық бар?', 1 from public.topics where title = '1000 көлеміндегі сандарды оқу және жазу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '203 санында неше ондық бар?', 'short_answer', '0'::jsonb, '203 = 200 + 0 + 3, демек ондықтар саны 0.', 'Ортаңғы цифрге қара.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '1000 көлеміндегі сандарды оқу және жазу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Разрядын тап', '480 санының жүздіктер разрядындағы цифры қандай?', 2 from public.topics where title = '1000 көлеміндегі сандарды оқу және жазу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '480 санының жүздіктер разрядындағы цифры қандай?', 'multiple_choice', '"4"'::jsonb, '480-нің бірінші цифрі 4 — жүздіктер.', 'Санның бірінші цифрі.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '1000 көлеміндегі сандарды оқу және жазу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('4', true, 0), ('8', false, 1), ('0', false, 2), ('48', false, 3)) as opt(text, is_correct, ord) where t2.title = '1000 көлеміндегі сандарды оқу және жазу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Санды құрастыр', '425 санын жүздік + ондық + бірлік түрінде құрастыр.', jsonb_build_object('kind', 'expression_builder', 'tiles', jsonb_build_array('400', '20', '5', '+', '+', '=', '425', '300', '7'), 'target', jsonb_build_array('400', '+', '20', '+', '5', '=', '425')), 3 from public.topics where title = '1000 көлеміндегі сандарды оқу және жазу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '425 санын жүздік + ондық + бірлік түрінде құрастыр.', 'expression_builder', '400 + 20 + 5 = 425'::jsonb, '425 = 400 + 20 + 5.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '1000 көлеміндегі сандарды оқу және жазу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 1000 болатын жүздіктерді сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(300,700), jsonb_build_array(600,400), jsonb_build_array(900,100), jsonb_build_array(800,200))), 4 from public.topics where title = '1000 көлеміндегі сандарды оқу және жазу' and grade = 2 and track = 'base';


-- ==== Үш таңбалы сандарды салыстыру (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Үш таңбалы сандарды разрядтары бойынша (жүздік → ондық → бірлік) салыстыру.' where title = 'Үш таңбалы сандарды салыстыру' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('452 мен 425 сандарын салыстырғанда алдымен жүздіктерін қараймыз — олар тең (4 = 4).', 'Содан кейін ондықтарын қараймыз: 5 > 2, демек 452 > 425.')), 0 from public.topics where title = 'Үш таңбалы сандарды салыстыру' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Екі санды салыстыр.', jsonb_build_object('kind', 'value-compare', 'labelA', '452', 'labelB', '425', 'numericA', 452, 'numericB', 425), 0 from public.topics where title = 'Үш таңбалы сандарды салыстыру' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Үш таңбалы сандарды салыстырғанда қандай ретпен қараймыз?', 0 from public.topics where title = 'Үш таңбалы сандарды салыстыру' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '683 пен 638 сандарының қайсысы үлкен? (үлкенін жаз)', '{}'::jsonb, 0 from public.topics where title = 'Үш таңбалы сандарды салыстыру' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '683 пен 638 сандарының қайсысы үлкен? (үлкенін жаз)', 'short_answer', '683'::jsonb, '683 > 638, себебі ондықтары 8 > 3.', 'Жүздіктері тең болса, ондықтарын салыстыр.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Үш таңбалы сандарды салыстыру' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Санды салыстыр', '719 бен 791 сандарының қайсысы кіші?', 0 from public.topics where title = 'Үш таңбалы сандарды салыстыру' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '719 бен 791 сандарының қайсысы кіші?', 'short_answer', '719'::jsonb, '719 < 791, себебі ондықтары 1 < 9.', 'Ондықтарын салыстыр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Үш таңбалы сандарды салыстыру' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Санды салыстыр', '905 бен 895 сандарының қайсысы үлкен?', 1 from public.topics where title = 'Үш таңбалы сандарды салыстыру' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '905 бен 895 сандарының қайсысы үлкен?', 'short_answer', '905'::jsonb, '905 > 895, себебі жүздіктері 9 > 8.', 'Жүздіктерін салыстыр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Үш таңбалы сандарды салыстыру' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Санды салыстыр', '360 мен 306 сандарының қайсысы үлкен?', 2 from public.topics where title = 'Үш таңбалы сандарды салыстыру' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '360 мен 306 сандарының қайсысы үлкен?', 'multiple_choice', '"360"'::jsonb, '360 > 306, себебі ондықтары 6 > 0.', 'Ондықтарын салыстыр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Үш таңбалы сандарды салыстыру' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('360', true, 0), ('306', false, 1), ('тең', false, 2), ('білмеймін', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Үш таңбалы сандарды салыстыру' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'ordering', 'Өсу ретімен тіз', 'Үш таңбалы сандарды өсу ретімен тіз.', jsonb_build_object('items', jsonb_build_array('258', '340', '512', '601')), 3 from public.topics where title = 'Үш таңбалы сандарды салыстыру' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 900 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(400,500), jsonb_build_array(350,550), jsonb_build_array(600,300), jsonb_build_array(700,200))), 4 from public.topics where title = 'Үш таңбалы сандарды салыстыру' and grade = 2 and track = 'base';


-- ==== 100 көлемінде қосу және азайту (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = '100 көлемінде екі таңбалы сандарды қосу және азайтуды меңгеру.' where title = '100 көлемінде қосу және азайту' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('34 + 25 есептегенде алдымен ондықтарды қосамыз: 30 + 20 = 50, содан кейін бірліктерді: 4 + 5 = 9, барлығы 59.', 'Азайту да дәл солай: ондықтарды, бірліктерді бөлек есептейміз.')), 0 from public.topics where title = '100 көлемінде қосу және азайту' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', null, jsonb_build_object('total', 20, 'startLeft', 14), 0 from public.topics where title = '100 көлемінде қосу және азайту' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Екі таңбалы сандарды қосқанда алдымен нені қосамыз?', 0 from public.topics where title = '100 көлемінде қосу және азайту' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Есепте: 34 + 25', '{}'::jsonb, 0 from public.topics where title = '100 көлемінде қосу және азайту' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Есепте: 34 + 25', 'short_answer', '59'::jsonb, '30 + 20 = 50, 4 + 5 = 9, 50 + 9 = 59.', 'Ондықтар мен бірліктерді бөлек қос.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = '100 көлемінде қосу және азайту' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Қос', '48 + 31 неше?', 0 from public.topics where title = '100 көлемінде қосу және азайту' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '48 + 31 неше?', 'short_answer', '79'::jsonb, '40+30=70, 8+1=9, 70+9=79.', 'Ондықтар мен бірліктерді бөлек қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '100 көлемінде қосу және азайту' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Азайт', '76 − 42 неше?', 1 from public.topics where title = '100 көлемінде қосу және азайту' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '76 − 42 неше?', 'short_answer', '34'::jsonb, '70−40=30, 6−2=4, 30+4=34.', 'Ондықтар мен бірліктерді бөлек азайт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '100 көлемінде қосу және азайту' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Қос', '53 + 26 нешеге тең?', 2 from public.topics where title = '100 көлемінде қосу және азайту' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '53 + 26 нешеге тең?', 'multiple_choice', '"79"'::jsonb, '50+20=70, 3+6=9, 70+9=79.', 'Ондықтар мен бірліктерді бөлек қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '100 көлемінде қосу және азайту' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('79', true, 0), ('78', false, 1), ('80', false, 2), ('69', false, 3)) as opt(text, is_correct, ord) where t2.title = '100 көлемінде қосу және азайту' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', '36 + 27 есебінің шешімін тексер.', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('30 + 20 = 50', '6 + 7 = 12', '50 + 12 = 62'), 'errorIndex', 1), 3 from public.topics where title = '100 көлемінде қосу және азайту' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '36 + 27 есебінің шешімін тексер.', 'find_error', '1'::jsonb, '6 + 7 = 13 (12 емес), дұрыс жауап 63.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '100 көлемінде қосу және азайту' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 100 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(45,55), jsonb_build_array(30,70), jsonb_build_array(62,38), jsonb_build_array(77,23))), 4 from public.topics where title = '100 көлемінде қосу және азайту' and grade = 2 and track = 'base';


-- ==== Жүздіктен аттап қосу және азайту (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Жүздіктен аттап қосу және азайтуды (мыс. 95 + 8, 102 − 6) меңгеру.' where title = 'Жүздіктен аттап қосу және азайту' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('95 + 8 есептегенде алдымен 95-ті 100-ге дейін толықтырамыз: 95 + 5 = 100, қалған 3-ті қосамыз: 100 + 3 = 103.', '102 − 6 есептегенде 100-ден 6-ны алып, қалған 2-ні қосамыз: 100 − 6 = 94, 94 + 2 = 96.')), 0 from public.topics where title = 'Жүздіктен аттап қосу және азайту' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', null, jsonb_build_object('total', 10, 'startLeft', 8), 0 from public.topics where title = 'Жүздіктен аттап қосу және азайту' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Жүздіктен аттап қосу тәсілінде алдымен нені толықтырамыз?', 0 from public.topics where title = 'Жүздіктен аттап қосу және азайту' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Жүздіктен аттап қос: 96 + 7', '{}'::jsonb, 0 from public.topics where title = 'Жүздіктен аттап қосу және азайту' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Жүздіктен аттап қос: 96 + 7', 'short_answer', '103'::jsonb, '96 + 4 = 100, 100 + 3 = 103.', '96-ны 100-ге дейін толықтыр.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Жүздіктен аттап қосу және азайту' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жүздіктен аттап қос', '98 + 5 неше?', 0 from public.topics where title = 'Жүздіктен аттап қосу және азайту' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '98 + 5 неше?', 'short_answer', '103'::jsonb, '98 + 2 = 100, 100 + 3 = 103.', '98-ді 100-ге дейін толықтыр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Жүздіктен аттап қосу және азайту' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жүздіктен аттап азайт', '103 − 6 неше?', 1 from public.topics where title = 'Жүздіктен аттап қосу және азайту' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '103 − 6 неше?', 'short_answer', '97'::jsonb, '103-ті 100 мен 3-ке бөл: 100−6=94, 94+3=97.', '103-ті 100 мен 3-ке бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Жүздіктен аттап қосу және азайту' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Жүздіктен аттап қос', '94 + 9 нешеге тең?', 2 from public.topics where title = 'Жүздіктен аттап қосу және азайту' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '94 + 9 нешеге тең?', 'multiple_choice', '"103"'::jsonb, '94 + 6 = 100, 100 + 3 = 103.', '94-ті 100-ге дейін толықтыр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Жүздіктен аттап қосу және азайту' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('103', true, 0), ('102', false, 1), ('104', false, 2), ('101', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Жүздіктен аттап қосу және азайту' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қадамды құрастыр', '97 + 6 есебін жүздіктен аттап шешу қадамын құрастыр: алдымен неше қосамыз?', jsonb_build_object('kind', 'expression_builder', 'tiles', jsonb_build_array('97', '+', '3', '=', '100', '2', '5'), 'target', jsonb_build_array('97', '+', '3', '=', '100')), 3 from public.topics where title = 'Жүздіктен аттап қосу және азайту' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '97 + 6 есебін жүздіктен аттап шешу қадамын құрастыр: алдымен неше қосамыз?', 'expression_builder', '97 + 3 = 100'::jsonb, '97-ні 100-ге дейін толықтыру үшін 3 керек.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Жүздіктен аттап қосу және азайту' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жүздікке толықтыратын жұптарды сәйкестендір', 'Қосындысы 100 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(95,5), jsonb_build_array(92,8), jsonb_build_array(97,3), jsonb_build_array(88,12))), 4 from public.topics where title = 'Жүздіктен аттап қосу және азайту' and grade = 2 and track = 'base';


-- ==== Көбейту ұғымы және көбейту кестесі (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Көбейтудің қайталанатын қосуға негізделгенін түсіну, көбейту кестесінің негіздерін меңгеру.' where title = 'Көбейту ұғымы және көбейту кестесі' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('3 + 3 + 3 + 3 — бұл 3-ті 4 рет қосу, оны қысқаша 3 × 4 деп жазамыз.', '3 × 4 = 12 — көбейту кестесінің бір мысалы.')), 0 from public.topics where title = 'Көбейту ұғымы және көбейту кестесі' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', '3-тен 4 топ жұлдызды санап, көбейтудің нәтижесін тексер.', jsonb_build_object('kind', 'count-click', 'icon', 'star', 'count', 12), 0 from public.topics where title = 'Көбейту ұғымы және көбейту кестесі' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Көбейту қайталанатын қандай амалды алмастырады?', 0 from public.topics where title = 'Көбейту ұғымы және көбейту кестесі' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '4-ті 5 рет қосса нешеге тең? (4 × 5)', '{}'::jsonb, 0 from public.topics where title = 'Көбейту ұғымы және көбейту кестесі' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '4-ті 5 рет қосса нешеге тең? (4 × 5)', 'short_answer', '20'::jsonb, '4 + 4 + 4 + 4 + 4 = 20, демек 4 × 5 = 20.', '4-ті 5 рет қос.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Көбейту ұғымы және көбейту кестесі' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Көбейт', '6 × 3 неше?', 0 from public.topics where title = 'Көбейту ұғымы және көбейту кестесі' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '6 × 3 неше?', 'short_answer', '18'::jsonb, '6 + 6 + 6 = 18.', '6-ны 3 рет қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көбейту ұғымы және көбейту кестесі' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Көбейт', '5 × 5 неше?', 1 from public.topics where title = 'Көбейту ұғымы және көбейту кестесі' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5 × 5 неше?', 'short_answer', '25'::jsonb, '5 + 5 + 5 + 5 + 5 = 25.', '5-ті 5 рет қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көбейту ұғымы және көбейту кестесі' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Көбейт', '7 × 2 нешеге тең?', 2 from public.topics where title = 'Көбейту ұғымы және көбейту кестесі' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '7 × 2 нешеге тең?', 'multiple_choice', '"14"'::jsonb, '7 + 7 = 14.', '7-ні 2 рет қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көбейту ұғымы және көбейту кестесі' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('14', true, 0), ('12', false, 1), ('16', false, 2), ('9', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Көбейту ұғымы және көбейту кестесі' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'ordering', 'Өсу ретімен тіз', 'Көбейтінділерді өсу ретімен тіз: 5 × 3, 2 × 3, 4 × 3, 3 × 3.', jsonb_build_object('items', jsonb_build_array('6', '9', '12', '15')), 3 from public.topics where title = 'Көбейту ұғымы және көбейту кестесі' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Көбейту кестесін сәйкестендір', '3-ке көбейту кестесі бойынша санды оның көбейтіндісімен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(2,6), jsonb_build_array(3,9), jsonb_build_array(4,12), jsonb_build_array(5,15))), 4 from public.topics where title = 'Көбейту ұғымы және көбейту кестесі' and grade = 2 and track = 'base';


-- ==== 2, 3, 4, 5-ке көбейту және бөлу (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = '2, 3, 4, 5 сандарына көбейту және бөлу кестесін меңгеру.' where title = '2, 3, 4, 5-ке көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('5-ке көбейту кестесі: 5×1=5, 5×2=10, 5×3=15...', 'Бөлу — көбейтудің кері амалы: 15 ÷ 5 = 3.')), 0 from public.topics where title = '2, 3, 4, 5-ке көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Көбейту кестесі бойынша мәнін тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('3', '×', '4', '=', '?'), 'blankIndex', 4, 'correctValue', '12'), 0 from public.topics where title = '2, 3, 4, 5-ке көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Бөлу амалы көбейтудің қандай амалы?', 0 from public.topics where title = '2, 3, 4, 5-ке көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '4 × 5 неше?', '{}'::jsonb, 0 from public.topics where title = '2, 3, 4, 5-ке көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '4 × 5 неше?', 'short_answer', '20'::jsonb, '4 × 5 = 20.', 'Көбейту кестесін пайдалан.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = '2, 3, 4, 5-ке көбейту және бөлу' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Көбейту кестесі', '2 × 9 неше?', 0 from public.topics where title = '2, 3, 4, 5-ке көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '2 × 9 неше?', 'short_answer', '18'::jsonb, '2 × 9 = 18.', 'Көбейту кестесін пайдалан.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '2, 3, 4, 5-ке көбейту және бөлу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Бөлу кестесі', '20 ÷ 4 неше?', 1 from public.topics where title = '2, 3, 4, 5-ке көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '20 ÷ 4 неше?', 'short_answer', '5'::jsonb, '20 ÷ 4 = 5.', '4 × 5 = 20 екенін еске түсір.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '2, 3, 4, 5-ке көбейту және бөлу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Көбейту кестесі', '3 × 5 нешеге тең?', 2 from public.topics where title = '2, 3, 4, 5-ке көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3 × 5 нешеге тең?', 'multiple_choice', '"15"'::jsonb, '3 × 5 = 15.', 'Көбейту кестесін пайдалан.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '2, 3, 4, 5-ке көбейту және бөлу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('15', true, 0), ('12', false, 1), ('18', false, 2), ('10', false, 3)) as opt(text, is_correct, ord) where t2.title = '2, 3, 4, 5-ке көбейту және бөлу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'drag_drop', 'Амалды ажырат', 'Әр өрнекті дұрыс топқа орналастыр.', jsonb_build_object('items', jsonb_build_array(jsonb_build_object('label', '3 × 4 = 12', 'group', 'a'), jsonb_build_object('label', '20 ÷ 5 = 4', 'group', 'b'), jsonb_build_object('label', '2 × 5 = 10', 'group', 'a'), jsonb_build_object('label', '15 ÷ 3 = 5', 'group', 'b')), 'groupALabel', 'Көбейту', 'groupBLabel', 'Бөлу'), 3 from public.topics where title = '2, 3, 4, 5-ке көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Көбейту кестесін сәйкестендір', '4-ке көбейту кестесі бойынша санды оның көбейтіндісімен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(2,8), jsonb_build_array(3,12), jsonb_build_array(5,20), jsonb_build_array(4,16))), 4 from public.topics where title = '2, 3, 4, 5-ке көбейту және бөлу' and grade = 2 and track = 'base';


-- ==== 6, 7, 8, 9-ға көбейту және бөлу (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = '6, 7, 8, 9 сандарына көбейту және бөлу кестесін меңгеру.' where title = '6, 7, 8, 9-ға көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('7-ге көбейту кестесі: 7×1=7, 7×2=14, 7×3=21...', 'Бөлу арқылы көбейтуді тексеруге болады: 21 ÷ 7 = 3.')), 0 from public.topics where title = '6, 7, 8, 9-ға көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Көбейту кестесі бойынша мәнін тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('7', '×', '3', '=', '?'), 'blankIndex', 4, 'correctValue', '21'), 0 from public.topics where title = '6, 7, 8, 9-ға көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Көбейту кестесін білу неге керек?', 0 from public.topics where title = '6, 7, 8, 9-ға көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '8 × 6 неше?', '{}'::jsonb, 0 from public.topics where title = '6, 7, 8, 9-ға көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '8 × 6 неше?', 'short_answer', '48'::jsonb, '8 × 6 = 48.', 'Көбейту кестесін пайдалан.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = '6, 7, 8, 9-ға көбейту және бөлу' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Көбейту кестесі', '9 × 4 неше?', 0 from public.topics where title = '6, 7, 8, 9-ға көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '9 × 4 неше?', 'short_answer', '36'::jsonb, '9 × 4 = 36.', 'Көбейту кестесін пайдалан.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '6, 7, 8, 9-ға көбейту және бөлу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Бөлу кестесі', '56 ÷ 7 неше?', 1 from public.topics where title = '6, 7, 8, 9-ға көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '56 ÷ 7 неше?', 'short_answer', '8'::jsonb, '56 ÷ 7 = 8.', '7 × 8 = 56 екенін еске түсір.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '6, 7, 8, 9-ға көбейту және бөлу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Көбейту кестесі', '6 × 8 нешеге тең?', 2 from public.topics where title = '6, 7, 8, 9-ға көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '6 × 8 нешеге тең?', 'multiple_choice', '"48"'::jsonb, '6 × 8 = 48.', 'Көбейту кестесін пайдалан.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '6, 7, 8, 9-ға көбейту және бөлу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('48', true, 0), ('42', false, 1), ('54', false, 2), ('40', false, 3)) as opt(text, is_correct, ord) where t2.title = '6, 7, 8, 9-ға көбейту және бөлу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', 'Көбейту кестесін тексер.', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('7 × 8 = 56', '8 × 7 = 56', '9 × 8 = 71'), 'errorIndex', 2), 3 from public.topics where title = '6, 7, 8, 9-ға көбейту және бөлу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Көбейту кестесін тексер.', 'find_error', '2'::jsonb, '9 × 8 = 72, 71 емес.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = '6, 7, 8, 9-ға көбейту және бөлу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Көбейту кестесін сәйкестендір', '7-ге көбейту кестесі бойынша санды оның көбейтіндісімен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(2,14), jsonb_build_array(3,21), jsonb_build_array(4,28), jsonb_build_array(5,35))), 4 from public.topics where title = '6, 7, 8, 9-ға көбейту және бөлу' and grade = 2 and track = 'base';


-- ==== Көбейту мен бөлудің өзара байланысы (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Көбейту мен бөлудің бір-бірімен кері байланысты амалдар екенін түсіну.' where title = 'Көбейту мен бөлудің өзара байланысы' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('6 × 7 = 42 болса, 42 ÷ 7 = 6 және 42 ÷ 6 = 7 да дұрыс.', 'Көбейту мен бөлу — бір-бірін тексеретін кері амалдар.')), 0 from public.topics where title = 'Көбейту мен бөлудің өзара байланысы' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', '6 × 7 = 42 екенін біле отырып, 42 ÷ 7 нешеге тең екенін тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('42', '÷', '7', '=', '?'), 'blankIndex', 4, 'correctValue', '6'), 0 from public.topics where title = 'Көбейту мен бөлудің өзара байланысы' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Көбейтуді бөлу арқылы қалай тексереміз?', 0 from public.topics where title = 'Көбейту мен бөлудің өзара байланысы' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '8 × 5 = 40 екені белгілі. 40 ÷ 5 нешеге тең?', '{}'::jsonb, 0 from public.topics where title = 'Көбейту мен бөлудің өзара байланысы' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '8 × 5 = 40 екені белгілі. 40 ÷ 5 нешеге тең?', 'short_answer', '8'::jsonb, 'Көбейту мен бөлу кері амалдар болғандықтан, 40 ÷ 5 = 8.', 'Көбейтіндіден бір көбейткішті бөл.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Көбейту мен бөлудің өзара байланысы' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Кері амалды тап', '9 × 4 = 36 екені белгілі. 36 ÷ 4 нешеге тең?', 0 from public.topics where title = 'Көбейту мен бөлудің өзара байланысы' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '9 × 4 = 36 екені белгілі. 36 ÷ 4 нешеге тең?', 'short_answer', '9'::jsonb, '36 ÷ 4 = 9.', 'Көбейтіндіден бір көбейткішті бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көбейту мен бөлудің өзара байланысы' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Кері амалды тап', '7 × 6 = 42 екені белгілі. 42 ÷ 6 нешеге тең?', 1 from public.topics where title = 'Көбейту мен бөлудің өзара байланысы' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '7 × 6 = 42 екені белгілі. 42 ÷ 6 нешеге тең?', 'short_answer', '7'::jsonb, '42 ÷ 6 = 7.', 'Көбейтіндіден бір көбейткішті бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көбейту мен бөлудің өзара байланысы' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Кері амалды тап', '5 × 8 = 40 екені белгілі. 40 ÷ 8 нешеге тең?', 2 from public.topics where title = 'Көбейту мен бөлудің өзара байланысы' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5 × 8 = 40 екені белгілі. 40 ÷ 8 нешеге тең?', 'multiple_choice', '"5"'::jsonb, '40 ÷ 8 = 5.', 'Көбейтіндіден бір көбейткішті бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көбейту мен бөлудің өзара байланысы' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('5', true, 0), ('8', false, 1), ('4', false, 2), ('6', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Көбейту мен бөлудің өзара байланысы' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Бөлу теңдігін құрастыр', '8 × 6 = 48 екені белгілі. Осыдан бөлу теңдігін құрастыр.', jsonb_build_object('kind', 'expression_builder', 'tiles', jsonb_build_array('48', '÷', '6', '=', '8', '7', '9'), 'target', jsonb_build_array('48', '÷', '6', '=', '8')), 3 from public.topics where title = 'Көбейту мен бөлудің өзара байланысы' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '8 × 6 = 48 екені белгілі. Осыдан бөлу теңдігін құрастыр.', 'expression_builder', '48 ÷ 6 = 8'::jsonb, '48 ÷ 6 = 8.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көбейту мен бөлудің өзара байланысы' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Бөлуді сәйкестендір', 'Көбейтіндіні 6-ға бөлгендегі бөлінділерін сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(42,7), jsonb_build_array(36,6), jsonb_build_array(54,9), jsonb_build_array(48,8))), 4 from public.topics where title = 'Көбейту мен бөлудің өзара байланысы' and grade = 2 and track = 'base';


-- ==== Белгісіз көбейткішті, бөлінгішті, бөлгішті табу (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Көбейту мен бөлу теңдеуіндегі белгісіз компонентті (көбейткіш, бөлінгіш, бөлгіш) табу.' where title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('x × 4 = 24 теңдеуінде x — белгісіз көбейткіш.', 'Оны табу үшін көбейтіндіні белгілі көбейткішке бөлеміз: x = 24 ÷ 4 = 6.')), 0 from public.topics where title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Белгісіз көбейткішті тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('?', '×', '4', '=', '24'), 'blankIndex', 0, 'correctValue', '6'), 0 from public.topics where title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Белгісіз көбейткішті табу үшін қандай амал қолданамыз?', 0 from public.topics where title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'x × 5 = 35. x неге тең?', '{}'::jsonb, 0 from public.topics where title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'x × 5 = 35. x неге тең?', 'short_answer', '7'::jsonb, '35 ÷ 5 = 7.', 'Көбейтіндіні белгілі көбейткішке бөл.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Бөлгішті тап', '36 ÷ x = 4. x (бөлгіш) неге тең?', 0 from public.topics where title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '36 ÷ x = 4. x (бөлгіш) неге тең?', 'short_answer', '9'::jsonb, '36 ÷ 4 = 9.', 'Бөлінгішті бөліндіге бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Бөлінгішті тап', 'x ÷ 6 = 7. x (бөлінгіш) неге тең?', 1 from public.topics where title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'x ÷ 6 = 7. x (бөлінгіш) неге тең?', 'short_answer', '42'::jsonb, '6 × 7 = 42.', 'Бөлгіш пен бөліндіні көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Көбейткішті тап', 'x × 8 = 48. x неге тең?', 2 from public.topics where title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'x × 8 = 48. x неге тең?', 'multiple_choice', '"6"'::jsonb, '48 ÷ 8 = 6.', 'Көбейтіндіні белгілі көбейткішке бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('6', true, 0), ('7', false, 1), ('8', false, 2), ('5', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'drag_drop', 'Белгісізді ажырат', 'Әр теңдеуде қай компонент белгісіз екенін ажырат.', jsonb_build_object('items', jsonb_build_array(jsonb_build_object('label', 'x × 5 = 20', 'group', 'a'), jsonb_build_object('label', '30 ÷ x = 6', 'group', 'b'), jsonb_build_object('label', 'x × 3 = 12', 'group', 'a'), jsonb_build_object('label', '24 ÷ x = 4', 'group', 'b')), 'groupALabel', 'Көбейткіш белгісіз', 'groupBLabel', 'Бөлгіш белгісіз'), 3 from public.topics where title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Көбейтіндіні сәйкестендір', 'Санды 5-ке көбейткендегі көбейтіндісін сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(3,15), jsonb_build_array(4,20), jsonb_build_array(6,30), jsonb_build_array(7,35))), 4 from public.topics where title = 'Белгісіз көбейткішті, бөлінгішті, бөлгішті табу' and grade = 2 and track = 'base';


-- ==== Екі амалмен шығарылатын мәтінді есептер (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Екі амал арқылы шығарылатын мәтін есептерді шешу.' where title = 'Екі амалмен шығарылатын мәтінді есептер' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Дүкенде 20 доп бар еді. Алдымен 8 доп сатылды, содан кейін тағы 15 доп әкелді.', 'Алдымен азайту, содан кейін қосу керек: 20 − 8 = 12, 12 + 15 = 27.')), 0 from public.topics where title = 'Екі амалмен шығарылатын мәтінді есептер' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Алдыңғы қадамнан кейін 12 доп қалды, ал 15 доп әкелінді. Қайсысы көп?', jsonb_build_object('kind', 'compare', 'iconA', 'ball', 'countA', 12, 'iconB', 'ball', 'countB', 15), 0 from public.topics where title = 'Екі амалмен шығарылатын мәтінді есептер' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Екі амалмен шығарылатын есепте қай амалды бірінші орындаймыз?', 0 from public.topics where title = 'Екі амалмен шығарылатын мәтінді есептер' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Сыныпта 24 оқушы бар еді. Алдымен 6 оқушы кетті, содан кейін тағы 9 оқушы келді. Енді сыныпта неше оқушы бар?', '{}'::jsonb, 0 from public.topics where title = 'Екі амалмен шығарылатын мәтінді есептер' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Сыныпта 24 оқушы бар еді. Алдымен 6 оқушы кетті, содан кейін тағы 9 оқушы келді. Енді сыныпта неше оқушы бар?', 'short_answer', '27'::jsonb, '24 − 6 = 18, 18 + 9 = 27.', 'Алдымен азайт, содан кейін қос.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Екі амалмен шығарылатын мәтінді есептер' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Екі амалмен шеш', 'Қоймада 35 жәшік бар еді. 12 жәшік әкетілді, содан кейін 8 жәшік әкелінді. Енді неше жәшік бар?', 0 from public.topics where title = 'Екі амалмен шығарылатын мәтінді есептер' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Қоймада 35 жәшік бар еді. 12 жәшік әкетілді, содан кейін 8 жәшік әкелінді. Енді неше жәшік бар?', 'short_answer', '31'::jsonb, '35 − 12 = 23, 23 + 8 = 31.', 'Алдымен азайт, содан кейін қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Екі амалмен шығарылатын мәтінді есептер' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Екі амалмен шеш', 'Аяулымда 40 теңге бар еді. Ол 15 теңгеге қалам, 10 теңгеге дәптер сатып алды. Неше теңгесі қалды?', 1 from public.topics where title = 'Екі амалмен шығарылатын мәтінді есептер' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Аяулымда 40 теңге бар еді. Ол 15 теңгеге қалам, 10 теңгеге дәптер сатып алды. Неше теңгесі қалды?', 'short_answer', '15'::jsonb, '40 − 15 − 10 = 15.', 'Екі шығынды да азайт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Екі амалмен шығарылатын мәтінді есептер' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Екі амалмен шеш', 'Бақшада 50 ағаш бар еді. Күзде 12 ағаш кесілді, көктемде 20 жаңа ағаш отырғызылды. Енді неше ағаш бар?', 2 from public.topics where title = 'Екі амалмен шығарылатын мәтінді есептер' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Бақшада 50 ағаш бар еді. Күзде 12 ағаш кесілді, көктемде 20 жаңа ағаш отырғызылды. Енді неше ағаш бар?', 'multiple_choice', '"58"'::jsonb, '50 − 12 = 38, 38 + 20 = 58.', 'Алдымен азайт, содан кейін қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Екі амалмен шығарылатын мәтінді есептер' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('58', true, 0), ('56', false, 1), ('60', false, 2), ('54', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Екі амалмен шығарылатын мәтінді есептер' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', 'Есепті тексер: Қоймада 40 қорап бар еді. 15 қорап әкетілді, 8 қорап әкелінді. Енді неше қорап бар?', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('40 − 15 = 25', '25 + 8 = 43'), 'errorIndex', 1), 3 from public.topics where title = 'Екі амалмен шығарылатын мәтінді есептер' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Есепті тексер: Қоймада 40 қорап бар еді. 15 қорап әкетілді, 8 қорап әкелінді. Енді неше қорап бар?', 'find_error', '1'::jsonb, '25 + 8 = 33, 43 емес.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Екі амалмен шығарылатын мәтінді есептер' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 50 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(18,32), jsonb_build_array(27,23), jsonb_build_array(14,36), jsonb_build_array(9,41))), 4 from public.topics where title = 'Екі амалмен шығарылатын мәтінді есептер' and grade = 2 and track = 'base';


-- ==== Есептерді сызба, қысқаша шарт арқылы шығару (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Есептің қысқаша шартын (кесте түрінде) құрып, оны шешуде қолдану.' where title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Қысқаша шарт есептің негізгі деректерін ықшам түрде көрсетеді: «Болды — 15, келді — 8, барлығы — ?».', 'Қысқаша шарт есепті шешуді жеңілдетеді.')), 0 from public.topics where title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', '«Болды — 15, келді — 8» жағдайын салыстыр.', jsonb_build_object('kind', 'compare', 'iconA', 'flower', 'countA', 15, 'iconB', 'flower', 'countB', 8), 0 from public.topics where title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Қысқаша шарт есепті шешуге қалай көмектеседі?', 0 from public.topics where title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Қысқаша шарт: «Болды — 22, кетті — 9, қалды — ?». Осы есепті шеш.', '{}'::jsonb, 0 from public.topics where title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Қысқаша шарт: «Болды — 22, кетті — 9, қалды — ?». Осы есепті шеш.', 'short_answer', '13'::jsonb, '22 − 9 = 13.', 'Азайту амалын қолдан.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Қысқаша шартпен шеш', 'Қысқаша шарт: «Болды — 18, әкелді — 14, барлығы — ?». Шеш.', 0 from public.topics where title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Қысқаша шарт: «Болды — 18, әкелді — 14, барлығы — ?». Шеш.', 'short_answer', '32'::jsonb, '18 + 14 = 32.', 'Қосу амалын қолдан.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Қысқаша шартпен шеш', 'Қысқаша шарт: «Болды — 30, берді — 12, қалды — ?». Шеш.', 1 from public.topics where title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Қысқаша шарт: «Болды — 30, берді — 12, қалды — ?». Шеш.', 'short_answer', '18'::jsonb, '30 − 12 = 18.', 'Азайту амалын қолдан.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Қысқаша шартпен шеш', 'Қысқаша шарт: «Болды — 25, кетті — 7, әкелді — 5, барлығы — ?». Шеш.', 2 from public.topics where title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Қысқаша шарт: «Болды — 25, кетті — 7, әкелді — 5, барлығы — ?». Шеш.', 'multiple_choice', '"23"'::jsonb, '25 − 7 = 18, 18 + 5 = 23.', 'Алдымен азайт, содан кейін қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('23', true, 0), ('22', false, 1), ('24', false, 2), ('20', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'drag_drop', 'Амалды таңда', 'Әр қысқаша шартқа қай амал керегін ажырат.', jsonb_build_object('items', jsonb_build_array(jsonb_build_object('label', 'Болды-12, әкелді-5, барлығы-?', 'group', 'a'), jsonb_build_object('label', 'Болды-20, кетті-7, қалды-?', 'group', 'b'), jsonb_build_object('label', 'Болды-8, тапты-6, барлығы-?', 'group', 'a'), jsonb_build_object('label', 'Болды-30, сатты-14, қалды-?', 'group', 'b')), 'groupALabel', 'Қосу керек', 'groupBLabel', 'Азайту керек'), 3 from public.topics where title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 40 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(18,22), jsonb_build_array(25,15), jsonb_build_array(9,31), jsonb_build_array(33,7))), 4 from public.topics where title = 'Есептерді сызба, қысқаша шарт арқылы шығару' and grade = 2 and track = 'base';


-- ==== Өрнектердегі амалдардың орындалу реті (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Бірнеше амалы бар өрнектерде амалдардың орындалу ретін (жақшасыз: көбейту/бөлу бірінші) білу.' where title = 'Өрнектердегі амалдардың орындалу реті' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('2 + 3 × 4 өрнегінде алдымен көбейтуді орындаймыз: 3 × 4 = 12, содан кейін қосамыз: 2 + 12 = 14.', 'Жақшасыз өрнекте көбейту мен бөлу қосу мен азайтудан бұрын орындалады.')), 0 from public.topics where title = 'Өрнектердегі амалдардың орындалу реті' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Амалдардың дұрыс ретімен өрнектің мәнін тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('2', '+', '3', '×', '4', '=', '?'), 'blankIndex', 6, 'correctValue', '14'), 0 from public.topics where title = 'Өрнектердегі амалдардың орындалу реті' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Жақшасыз өрнекте қай амал бірінші орындалады?', 0 from public.topics where title = 'Өрнектердегі амалдардың орындалу реті' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '5 + 2 × 6 өрнегінің мәнін тап.', '{}'::jsonb, 0 from public.topics where title = 'Өрнектердегі амалдардың орындалу реті' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5 + 2 × 6 өрнегінің мәнін тап.', 'short_answer', '17'::jsonb, 'Алдымен 2 × 6 = 12, содан кейін 5 + 12 = 17.', 'Алдымен көбейтуді орында.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Өрнектердегі амалдардың орындалу реті' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Реті бойынша есепте', '10 − 2 × 3 өрнегінің мәні нешеге тең?', 0 from public.topics where title = 'Өрнектердегі амалдардың орындалу реті' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '10 − 2 × 3 өрнегінің мәні нешеге тең?', 'short_answer', '4'::jsonb, '2 × 3 = 6, 10 − 6 = 4.', 'Алдымен көбейтуді орында.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Өрнектердегі амалдардың орындалу реті' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Реті бойынша есепте', '4 × 3 + 5 өрнегінің мәні нешеге тең?', 1 from public.topics where title = 'Өрнектердегі амалдардың орындалу реті' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '4 × 3 + 5 өрнегінің мәні нешеге тең?', 'short_answer', '17'::jsonb, '4 × 3 = 12, 12 + 5 = 17.', 'Алдымен көбейтуді орында.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Өрнектердегі амалдардың орындалу реті' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Реті бойынша есепте', '20 − 3 × 4 өрнегінің мәні нешеге тең?', 2 from public.topics where title = 'Өрнектердегі амалдардың орындалу реті' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '20 − 3 × 4 өрнегінің мәні нешеге тең?', 'multiple_choice', '"8"'::jsonb, '3 × 4 = 12, 20 − 12 = 8.', 'Алдымен көбейтуді орында.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Өрнектердегі амалдардың орындалу реті' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('8', true, 0), ('68', false, 1), ('7', false, 2), ('9', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Өрнектердегі амалдардың орындалу реті' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', '15 − 2 × 5 өрнегінің шешімін тексер.', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('15 − 2 = 13', '13 × 5 = 65'), 'errorIndex', 0), 3 from public.topics where title = 'Өрнектердегі амалдардың орындалу реті' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '15 − 2 × 5 өрнегінің шешімін тексер.', 'find_error', '0'::jsonb, 'Алдымен көбейтуді орындау керек: 2 × 5 = 10, 15 − 10 = 5. Бастапқы қадам қате.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Өрнектердегі амалдардың орындалу реті' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 20 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(13,7), jsonb_build_array(9,11), jsonb_build_array(16,4), jsonb_build_array(18,2))), 4 from public.topics where title = 'Өрнектердегі амалдардың орындалу реті' and grade = 2 and track = 'base';


-- ==== Шамалар: ұзындық, масса, уақыт, көлем (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Ұзындық, масса, уақыт, көлем өлшем бірліктерін білу және оларды түрлендіру.' where title = 'Шамалар: ұзындық, масса, уақыт, көлем' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'infographic', null, null, jsonb_build_object('kind', 'scene', 'items', jsonb_build_array(jsonb_build_object('icon', '📏', 'label', 'Ұзындық'), jsonb_build_object('icon', '⚖️', 'label', 'Масса'), jsonb_build_object('icon', '⏰', 'label', 'Уақыт'), jsonb_build_object('icon', '💧', 'label', 'Көлем')), 'caption', '1 килограмда 1000 грамм бар (1 кг = 1000 г), 1 литрде 1000 миллилитр бар (1 л = 1000 мл) — әр шаманың өз өлшем бірліктері бар.'), 0 from public.topics where title = 'Шамалар: ұзындық, масса, уақыт, көлем' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Қайсысы ауыр екенін салыстыр.', jsonb_build_object('kind', 'value-compare', 'labelA', '1 кг (граммен)', 'labelB', '900 г', 'numericA', 1000, 'numericB', 900), 0 from public.topics where title = 'Шамалар: ұзындық, масса, уақыт, көлем' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Масса мен көлемнің негізгі өлшем бірліктері қандай?', 0 from public.topics where title = 'Шамалар: ұзындық, масса, уақыт, көлем' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '2 кг неше грамм?', '{}'::jsonb, 0 from public.topics where title = 'Шамалар: ұзындық, масса, уақыт, көлем' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '2 кг неше грамм?', 'short_answer', '2000'::jsonb, '2 × 1000 = 2000 г.', '1000-ды 2-ге көбейт.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Шамалар: ұзындық, масса, уақыт, көлем' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Түрлендір', '3 литр неше миллилитр?', 0 from public.topics where title = 'Шамалар: ұзындық, масса, уақыт, көлем' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3 литр неше миллилитр?', 'short_answer', '3000'::jsonb, '3 × 1000 = 3000 мл.', '1000-ды 3-ке көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Шамалар: ұзындық, масса, уақыт, көлем' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Түрлендір', '1500 грамм — толық неше килограмм?', 1 from public.topics where title = 'Шамалар: ұзындық, масса, уақыт, көлем' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '1500 грамм — толық неше килограмм?', 'short_answer', '1'::jsonb, '1500 г = 1 кг 500 г, демек толық 1 килограмм.', '1000 г = 1 кг.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Шамалар: ұзындық, масса, уақыт, көлем' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Түрлендір', '5 кг неше грамм?', 2 from public.topics where title = 'Шамалар: ұзындық, масса, уақыт, көлем' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5 кг неше грамм?', 'multiple_choice', '"5000"'::jsonb, '5 × 1000 = 5000 г.', '1000-ды 5-ке көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Шамалар: ұзындық, масса, уақыт, көлем' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('5000', true, 0), ('500', false, 1), ('50000', false, 2), ('50', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Шамалар: ұзындық, масса, уақыт, көлем' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'drag_drop', 'Бірлікті ажырат', 'Әр өлшем бірлігін дұрыс топқа орналастыр.', jsonb_build_object('items', jsonb_build_array(jsonb_build_object('label', 'грамм', 'group', 'a'), jsonb_build_object('label', 'литр', 'group', 'b'), jsonb_build_object('label', 'килограмм', 'group', 'a'), jsonb_build_object('label', 'миллилитр', 'group', 'b')), 'groupALabel', 'Масса бірлігі', 'groupBLabel', 'Көлем бірлігі'), 3 from public.topics where title = 'Шамалар: ұзындық, масса, уақыт, көлем' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Килограмды граммен сәйкестендір', 'Килограм санын оған сәйкес грамм санымен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(1,1000), jsonb_build_array(2,2000), jsonb_build_array(3,3000), jsonb_build_array(5,5000))), 4 from public.topics where title = 'Шамалар: ұзындық, масса, уақыт, көлем' and grade = 2 and track = 'base';


-- ==== Геометриялық фигуралардың периметрі (2-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Тіктөртбұрыш, шаршы, үшбұрыштың периметрін есептеу.' where title = 'Геометриялық фигуралардың периметрі' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Периметр — фигураның барлық қабырғаларының қосындысы.', 'Тіктөртбұрыштың периметрі = 2 × (ені + ұзындығы).')), 0 from public.topics where title = 'Геометриялық фигуралардың периметрі' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Тіктөртбұрыштың периметрін тап.', jsonb_build_object('kind', 'perimeter', 'width', 5, 'height', 3, 'unit', 'см'), 0 from public.topics where title = 'Геометриялық фигуралардың периметрі' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Периметрді есептеу үшін не істейміз?', 0 from public.topics where title = 'Геометриялық фигуралардың периметрі' and grade = 2 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Қабырғасы 6 см шаршының периметрін тап.', '{}'::jsonb, 0 from public.topics where title = 'Геометриялық фигуралардың периметрі' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Қабырғасы 6 см шаршының периметрін тап.', 'short_answer', '24'::jsonb, '6 × 4 = 24 см (шаршының 4 қабырғасы тең).', 'Қабырғаны 4-ке көбейт.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Геометриялық фигуралардың периметрі' and tp.grade = 2 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Периметрін тап', 'Ені 4 см, ұзындығы 7 см тіктөртбұрыштың периметрін тап.', 0 from public.topics where title = 'Геометриялық фигуралардың периметрі' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Ені 4 см, ұзындығы 7 см тіктөртбұрыштың периметрін тап.', 'short_answer', '22'::jsonb, '2 × (4 + 7) = 22 см.', 'Ені мен ұзындықты қосып, 2-ге көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Геометриялық фигуралардың периметрі' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Периметрін тап', 'Қабырғалары 5 см, 6 см, 7 см үшбұрыштың периметрін тап.', 1 from public.topics where title = 'Геометриялық фигуралардың периметрі' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Қабырғалары 5 см, 6 см, 7 см үшбұрыштың периметрін тап.', 'short_answer', '18'::jsonb, '5 + 6 + 7 = 18 см.', 'Үш қабырғаны қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Геометриялық фигуралардың периметрі' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Периметрін тап', 'Қабырғасы 9 см шаршының периметрі нешеге тең?', 2 from public.topics where title = 'Геометриялық фигуралардың периметрі' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Қабырғасы 9 см шаршының периметрі нешеге тең?', 'multiple_choice', '"36"'::jsonb, '9 × 4 = 36 см.', 'Қабырғаны 4-ке көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Геометриялық фигуралардың периметрі' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('36', true, 0), ('18', false, 1), ('27', false, 2), ('45', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Геометриялық фигуралардың периметрі' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қабырғаны өлш', 'Тіктөртбұрыштың бір қабырғасын сызғышпен өлш.', jsonb_build_object('kind', 'measurement', 'unit', 'см', 'length', 6, 'maxScale', 12), 3 from public.topics where title = 'Геометриялық фигуралардың периметрі' and grade = 2 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Тіктөртбұрыштың бір қабырғасын сызғышпен өлш.', 'measurement', '6'::jsonb, 'Сызғыш бойынша қабырға ұзындығы 6 см.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Геометриялық фигуралардың периметрі' and t2.grade = 2 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Периметрді сәйкестендір', 'Шаршының қабырғасын оның периметрімен сәйкестендір (қабырға × 4):', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(3,12), jsonb_build_array(5,20), jsonb_build_array(6,24), jsonb_build_array(7,28))), 4 from public.topics where title = 'Геометриялық фигуралардың периметрі' and grade = 2 and track = 'base';

