-- Generated by scripts/generateLessonSeed.ts from src/data/lessonContent/grade4Base.ts.
-- Do not hand-edit — change the content module and regenerate instead.
-- ==== Көптаңбалы сандарды оқу, жазу және салыстыру (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Көптаңбалы (мың, миллион) сандарды дұрыс оқу, жазу және салыстыру.' where title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('245 678 саны «екі жүз қырық бес мың алты жүз жетпіс сегіз» деп оқылады.', 'Көптаңбалы сандарды салыстырғанда алдымен цифр санын, содан кейін жоғарғы разрядтарды қараймыз.')), 0 from public.topics where title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Екі санды салыстыр.', jsonb_build_object('kind', 'value-compare', 'labelA', '245 678', 'labelB', '245 687', 'numericA', 245678, 'numericB', 245687), 0 from public.topics where title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Екі санның цифр саны әртүрлі болса, қайсысы үлкен болады?', 0 from public.topics where title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '3 458 пен 3 485 сандарының қайсысы үлкен? (үлкенін жаз)', '{}'::jsonb, 0 from public.topics where title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3 458 пен 3 485 сандарының қайсысы үлкен? (үлкенін жаз)', 'short_answer', '3485'::jsonb, '3485 > 3458, себебі ондықтары 8 > 5.', 'Жүздіктері тең болса, ондықтарын салыстыр.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Санды салыстыр', '12 340 пен 12 430 сандарының қайсысы кіші?', 0 from public.topics where title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '12 340 пен 12 430 сандарының қайсысы кіші?', 'short_answer', '12340'::jsonb, '12340 < 12430, себебі жүздіктері 3 < 4.', 'Жүздіктерін салыстыр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Санды салыстыр', '999 бен 1000 сандарының қайсысы үлкен?', 1 from public.topics where title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '999 бен 1000 сандарының қайсысы үлкен?', 'short_answer', '1000'::jsonb, '1000 > 999, себебі цифр саны көп.', 'Цифр санын салыстыр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Санды салыстыр', '56 789 бен 56 798 сандарының қайсысы үлкен?', 2 from public.topics where title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '56 789 бен 56 798 сандарының қайсысы үлкен?', 'multiple_choice', '"56798"'::jsonb, '56798 > 56789, себебі ондықтары 9 > 8.', 'Ондықтарын салыстыр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('56798', true, 0), ('56789', false, 1), ('тең', false, 2), ('білмеймін', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'ordering', 'Өсу ретімен тіз', 'Сандарды өсу ретімен тіз.', jsonb_build_object('items', jsonb_build_array('999', '1000', '12340', '12430')), 3 from public.topics where title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 1000 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(400,600), jsonb_build_array(250,750), jsonb_build_array(820,180), jsonb_build_array(999,1))), 4 from public.topics where title = 'Көптаңбалы сандарды оқу, жазу және салыстыру' and grade = 4 and track = 'base';


-- ==== Көптаңбалы сандардың разрядтық құрамы (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Көптаңбалы сандардың мыңдық, жүздік, ондық, бірлік разрядтарынан тұратын құрамын анықтау.' where title = 'Көптаңбалы сандардың разрядтық құрамы' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('3452 = 3000 + 400 + 50 + 2.', 'Мыңдықтар, жүздіктер, ондықтар, бірліктер — әрқайсысының өз орны бар.')), 0 from public.topics where title = 'Көптаңбалы сандардың разрядтық құрамы' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', '3452 санының бірліктер разрядындағы жасырын цифрды тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('3', '4', '5', '?'), 'blankIndex', 3, 'correctValue', '2'), 0 from public.topics where title = 'Көптаңбалы сандардың разрядтық құрамы' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Төрт таңбалы санда неше разряд бар?', 0 from public.topics where title = 'Көптаңбалы сандардың разрядтық құрамы' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '6 209 санында неше мыңдық бар?', '{}'::jsonb, 0 from public.topics where title = 'Көптаңбалы сандардың разрядтық құрамы' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '6 209 санында неше мыңдық бар?', 'short_answer', '6'::jsonb, '6209 = 6000 + 200 + 0 + 9.', 'Санның бірінші цифрі.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Көптаңбалы сандардың разрядтық құрамы' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Разрядын тап', '5 083 санында неше ондық бар?', 0 from public.topics where title = 'Көптаңбалы сандардың разрядтық құрамы' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5 083 санында неше ондық бар?', 'short_answer', '8'::jsonb, '5083 = 5000 + 0 + 80 + 3.', 'Үшінші цифрге қара.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандардың разрядтық құрамы' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Разрядын тап', '7 400 санында неше жүздік бар?', 1 from public.topics where title = 'Көптаңбалы сандардың разрядтық құрамы' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '7 400 санында неше жүздік бар?', 'short_answer', '4'::jsonb, '7400 = 7000 + 400.', 'Екінші цифрге қара.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандардың разрядтық құрамы' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Разрядын тап', '9 156 санының мыңдықтар разрядындағы цифры қандай?', 2 from public.topics where title = 'Көптаңбалы сандардың разрядтық құрамы' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '9 156 санының мыңдықтар разрядындағы цифры қандай?', 'multiple_choice', '"9"'::jsonb, 'Санның бірінші цифрі 9 — мыңдықтар.', 'Санның бірінші цифрі.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандардың разрядтық құрамы' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('9', true, 0), ('1', false, 1), ('5', false, 2), ('6', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Көптаңбалы сандардың разрядтық құрамы' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Санды құрастыр', '5083 санын мыңдық + ондық + бірлік түрінде құрастыр.', jsonb_build_object('kind', 'expression_builder', 'tiles', jsonb_build_array('5000', '80', '3', '+', '+', '=', '5083', '4000', '30'), 'target', jsonb_build_array('5000', '+', '80', '+', '3', '=', '5083')), 3 from public.topics where title = 'Көптаңбалы сандардың разрядтық құрамы' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5083 санын мыңдық + ондық + бірлік түрінде құрастыр.', 'expression_builder', to_jsonb('5000 + 80 + 3 = 5083'::text), '5083 = 5000 + 80 + 3.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандардың разрядтық құрамы' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Мыңдықты мәнімен сәйкестендір', 'Мыңдық санын оның мәнімен сәйкестендір (мыңдық × 1000):', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(3,3000), jsonb_build_array(5,5000), jsonb_build_array(7,7000), jsonb_build_array(9,9000))), 4 from public.topics where title = 'Көптаңбалы сандардың разрядтық құрамы' and grade = 4 and track = 'base';


-- ==== Көптаңбалы сандарды жазбаша қосу (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Көптаңбалы сандарды жазбаша (бағанмен) қосуды меңгеру.' where title = 'Көптаңбалы сандарды жазбаша қосу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('2 456 + 1 378 жазбаша қосқанда бірліктен бастаймыз: 6+8=14 (4 жаз, 1 артық)...', 'Артық сандарды әрдайым келесі разрядқа қосамыз.')), 0 from public.topics where title = 'Көптаңбалы сандарды жазбаша қосу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', null, jsonb_build_object('total', 10, 'startLeft', 6), 0 from public.topics where title = 'Көптаңбалы сандарды жазбаша қосу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Жазбаша қосуда қай разрядтан бастаймыз?', 0 from public.topics where title = 'Көптаңбалы сандарды жазбаша қосу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Жазбаша қос: 2456 + 1378', '{}'::jsonb, 0 from public.topics where title = 'Көптаңбалы сандарды жазбаша қосу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Жазбаша қос: 2456 + 1378', 'short_answer', '3834'::jsonb, '2456 + 1378 = 3834.', 'Бірліктен бастап, артықты келесі разрядқа қос.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Көптаңбалы сандарды жазбаша қосу' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жазбаша қос', '3 245 + 2 867 неше?', 0 from public.topics where title = 'Көптаңбалы сандарды жазбаша қосу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3 245 + 2 867 неше?', 'short_answer', '6112'::jsonb, '3245 + 2867 = 6112.', 'Бірліктен бастап, артықты келесі разрядқа қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандарды жазбаша қосу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жазбаша қос', '4 567 + 3 456 неше?', 1 from public.topics where title = 'Көптаңбалы сандарды жазбаша қосу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '4 567 + 3 456 неше?', 'short_answer', '8023'::jsonb, '4567 + 3456 = 8023.', 'Бірліктен бастап, артықты келесі разрядқа қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандарды жазбаша қосу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Жазбаша қос', '5 678 + 2 345 нешеге тең?', 2 from public.topics where title = 'Көптаңбалы сандарды жазбаша қосу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5 678 + 2 345 нешеге тең?', 'multiple_choice', '"8023"'::jsonb, '5678 + 2345 = 8023.', 'Бірліктен бастап, артықты келесі разрядқа қос.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандарды жазбаша қосу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('8023', true, 0), ('7923', false, 1), ('8123', false, 2), ('8033', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Көптаңбалы сандарды жазбаша қосу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', '3245 + 2867 жазбаша қосу шешімін тексер.', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('5 + 7 = 12 (2 жаз, 1 артық)', '4 + 6 + 1 = 10 (0 жаз, 1 артық)', '2 + 8 + 1 = 11 (1 жаз, 1 артық)', '3 + 2 + 1 = 6'), 'errorIndex', 1), 3 from public.topics where title = 'Көптаңбалы сандарды жазбаша қосу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3245 + 2867 жазбаша қосу шешімін тексер.', 'find_error', '1'::jsonb, '4 + 6 + 1 = 11, 10 емес.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандарды жазбаша қосу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 10000 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(4000,6000), jsonb_build_array(2500,7500), jsonb_build_array(1000,9000), jsonb_build_array(3500,6500))), 4 from public.topics where title = 'Көптаңбалы сандарды жазбаша қосу' and grade = 4 and track = 'base';


-- ==== Көптаңбалы сандарды жазбаша азайту (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Көптаңбалы сандарды жазбаша (бағанмен) азайтуды меңгеру.' where title = 'Көптаңбалы сандарды жазбаша азайту' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('5 234 − 1 876 жазбаша азайтқанда 4-тен 6-ны алу мүмкін емес, көрші разрядтан қарыз аламыз.', 'Қарызды әрдайым көрші (жоғарырақ) разрядтан аламыз.')), 0 from public.topics where title = 'Көптаңбалы сандарды жазбаша азайту' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', null, jsonb_build_object('total', 10, 'startLeft', 4), 0 from public.topics where title = 'Көптаңбалы сандарды жазбаша азайту' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Жазбаша азайтуда жетпей қалса не істейміз?', 0 from public.topics where title = 'Көптаңбалы сандарды жазбаша азайту' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Жазбаша азайт: 5234 − 1876', '{}'::jsonb, 0 from public.topics where title = 'Көптаңбалы сандарды жазбаша азайту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Жазбаша азайт: 5234 − 1876', 'short_answer', '3358'::jsonb, '5234 − 1876 = 3358.', 'Жетпесе, көрші разрядтан қарыз ал.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Көптаңбалы сандарды жазбаша азайту' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жазбаша азайт', '6 512 − 2 748 неше?', 0 from public.topics where title = 'Көптаңбалы сандарды жазбаша азайту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '6 512 − 2 748 неше?', 'short_answer', '3764'::jsonb, '6512 − 2748 = 3764.', 'Жетпесе, көрші разрядтан қарыз ал.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандарды жазбаша азайту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жазбаша азайт', '8 000 − 3 456 неше?', 1 from public.topics where title = 'Көптаңбалы сандарды жазбаша азайту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '8 000 − 3 456 неше?', 'short_answer', '4544'::jsonb, '8000 − 3456 = 4544.', 'Жетпесе, көрші разрядтан қарыз ал.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандарды жазбаша азайту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Жазбаша азайт', '7 305 − 2 468 нешеге тең?', 2 from public.topics where title = 'Көптаңбалы сандарды жазбаша азайту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '7 305 − 2 468 нешеге тең?', 'multiple_choice', '"4837"'::jsonb, '7305 − 2468 = 4837.', 'Жетпесе, көрші разрядтан қарыз ал.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандарды жазбаша азайту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('4837', true, 0), ('4937', false, 1), ('4747', false, 2), ('4827', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Көптаңбалы сандарды жазбаша азайту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', '8000 − 3456 жазбаша азайту шешімін тексер.', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('Бірліктен басталады: 0-ден 6-ны алу үшін қарыз аламыз', '8000 − 3456 = 4644'), 'errorIndex', 1), 3 from public.topics where title = 'Көптаңбалы сандарды жазбаша азайту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '8000 − 3456 жазбаша азайту шешімін тексер.', 'find_error', '1'::jsonb, '8000 − 3456 = 4544, 4644 емес.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы сандарды жазбаша азайту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 8000 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(3456,4544), jsonb_build_array(2000,6000), jsonb_build_array(5000,3000), jsonb_build_array(1500,6500))), 4 from public.topics where title = 'Көптаңбалы сандарды жазбаша азайту' and grade = 4 and track = 'base';


-- ==== Көптаңбалы санды бір таңбалы санға көбейту (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Көптаңбалы санды бір таңбалы санға жазбаша көбейтуді меңгеру.' where title = 'Көптаңбалы санды бір таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('1234 × 3 есептегенде әр разрядты бөлек көбейтіп, артықтарды қосамыз.', 'Нәтиже: 1234 × 3 = 3702.')), 0 from public.topics where title = 'Көптаңбалы санды бір таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', null, jsonb_build_object('total', 20, 'startLeft', 17), 0 from public.topics where title = 'Көптаңбалы санды бір таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Көптаңбалы санды бір таңбалы санға көбейткенде қай разрядтан бастаймыз?', 0 from public.topics where title = 'Көптаңбалы санды бір таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '1234 × 3 неше?', '{}'::jsonb, 0 from public.topics where title = 'Көптаңбалы санды бір таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '1234 × 3 неше?', 'short_answer', '3702'::jsonb, '1234 × 3 = 3702.', 'Бірліктен бастап көбейт, артықты келесі разрядқа қос.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Көптаңбалы санды бір таңбалы санға көбейту' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Көбейт', '2 123 × 4 неше?', 0 from public.topics where title = 'Көптаңбалы санды бір таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '2 123 × 4 неше?', 'short_answer', '8492'::jsonb, '2123 × 4 = 8492.', 'Бірліктен бастап көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы санды бір таңбалы санға көбейту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Көбейт', '3 142 × 2 неше?', 1 from public.topics where title = 'Көптаңбалы санды бір таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3 142 × 2 неше?', 'short_answer', '6284'::jsonb, '3142 × 2 = 6284.', 'Бірліктен бастап көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы санды бір таңбалы санға көбейту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Көбейт', '1 021 × 5 нешеге тең?', 2 from public.topics where title = 'Көптаңбалы санды бір таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '1 021 × 5 нешеге тең?', 'multiple_choice', '"5105"'::jsonb, '1021 × 5 = 5105.', 'Бірліктен бастап көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы санды бір таңбалы санға көбейту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('5105', true, 0), ('5015', false, 1), ('5155', false, 2), ('5025', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Көптаңбалы санды бір таңбалы санға көбейту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Көбейтуді құрастыр', '2123 × 4 есебінің бірінші қадамын құрастыр.', jsonb_build_object('kind', 'expression_builder', 'tiles', jsonb_build_array('2000', '×', '4', '=', '8000', '7000', '9000'), 'target', jsonb_build_array('2000', '×', '4', '=', '8000')), 3 from public.topics where title = 'Көптаңбалы санды бір таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '2123 × 4 есебінің бірінші қадамын құрастыр.', 'expression_builder', to_jsonb('2000 × 4 = 8000'::text), '2000 × 4 = 8000.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы санды бір таңбалы санға көбейту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Көбейтіндіні сәйкестендір', 'Санды оның 4-ке көбейтіндісімен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(1000,4000), jsonb_build_array(2000,8000), jsonb_build_array(1500,6000), jsonb_build_array(500,2000))), 4 from public.topics where title = 'Көптаңбалы санды бір таңбалы санға көбейту' and grade = 4 and track = 'base';


-- ==== Көптаңбалы санды екі таңбалы санға көбейту (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Көптаңбалы санды екі таңбалы санға (екі қадаммен) көбейтуді меңгеру.' where title = 'Көптаңбалы санды екі таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('124 × 23 есептегенде алдымен 124×20=2480, содан кейін 124×3=372, соңында қосамыз: 2480+372=2852.', 'Екі таңбалы санға көбейткенде оны ондық пен бірлікке бөліп, екі рет көбейтеміз.')), 0 from public.topics where title = 'Көптаңбалы санды екі таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', null, jsonb_build_object('total', 23, 'startLeft', 20), 0 from public.topics where title = 'Көптаңбалы санды екі таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Екі таңбалы санға көбейткенде санды қалай бөлеміз?', 0 from public.topics where title = 'Көптаңбалы санды екі таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '124 × 23 неше?', '{}'::jsonb, 0 from public.topics where title = 'Көптаңбалы санды екі таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '124 × 23 неше?', 'short_answer', '2852'::jsonb, '124×20=2480, 124×3=372, 2480+372=2852.', '23-ті 20 мен 3-ке бөл.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Көптаңбалы санды екі таңбалы санға көбейту' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Көбейт', '215 × 12 неше?', 0 from public.topics where title = 'Көптаңбалы санды екі таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '215 × 12 неше?', 'short_answer', '2580'::jsonb, '215×10=2150, 215×2=430, 2150+430=2580.', '12-ні 10 мен 2-ге бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы санды екі таңбалы санға көбейту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Көбейт', '134 × 21 неше?', 1 from public.topics where title = 'Көптаңбалы санды екі таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '134 × 21 неше?', 'short_answer', '2814'::jsonb, '134×20=2680, 134×1=134, 2680+134=2814.', '21-ді 20 мен 1-ге бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы санды екі таңбалы санға көбейту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Көбейт', '112 × 15 нешеге тең?', 2 from public.topics where title = 'Көптаңбалы санды екі таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '112 × 15 нешеге тең?', 'multiple_choice', '"1680"'::jsonb, '112×10=1120, 112×5=560, 1120+560=1680.', '15-ті 10 мен 5-ке бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы санды екі таңбалы санға көбейту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('1680', true, 0), ('1580', false, 1), ('1780', false, 2), ('1670', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Көптаңбалы санды екі таңбалы санға көбейту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', '215 × 12 есебінің шешімін тексер.', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('215 × 10 = 2150', '215 × 2 = 420', '2150 + 420 = 2570'), 'errorIndex', 1), 3 from public.topics where title = 'Көптаңбалы санды екі таңбалы санға көбейту' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '215 × 12 есебінің шешімін тексер.', 'find_error', '1'::jsonb, '215 × 2 = 430, 420 емес. Дұрыс жауап 2580.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы санды екі таңбалы санға көбейту' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Көбейтіндіні сәйкестендір', 'Санды оның 12-ге көбейтіндісімен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(100,1200), jsonb_build_array(200,2400), jsonb_build_array(50,600), jsonb_build_array(10,120))), 4 from public.topics where title = 'Көптаңбалы санды екі таңбалы санға көбейту' and grade = 4 and track = 'base';


-- ==== Көптаңбалы санды бір және екі таңбалы санға бөлу (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Көптаңбалы санды бір және екі таңбалы санға бөлуді меңгеру.' where title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('936 ÷ 3 есептегенде үлкен разрядтан бастап бөлеміз: 9÷3=3, 3÷3=1, 6÷3=2, нәтиже 312.', 'Екі таңбалы санға бөлу де дәл осындай ретпен орындалады.')), 0 from public.topics where title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Бөлудің нәтижесін тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('936', '÷', '3', '=', '?'), 'blankIndex', 4, 'correctValue', '312'), 0 from public.topics where title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Бөлуде қай разрядтан бастаймыз?', 0 from public.topics where title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '868 ÷ 4 неше?', '{}'::jsonb, 0 from public.topics where title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '868 ÷ 4 неше?', 'short_answer', '217'::jsonb, '868 ÷ 4 = 217.', 'Үлкен разрядтан бастап бөл.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Бөл', '936 ÷ 3 неше?', 0 from public.topics where title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '936 ÷ 3 неше?', 'short_answer', '312'::jsonb, '936 ÷ 3 = 312.', 'Үлкен разрядтан бастап бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Екі таңбалыға бөл', '480 ÷ 24 неше?', 1 from public.topics where title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '480 ÷ 24 неше?', 'short_answer', '20'::jsonb, '480 ÷ 24 = 20.', '24 × 20 = 480 екенін тексер.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Бөл', '672 ÷ 6 нешеге тең?', 2 from public.topics where title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '672 ÷ 6 нешеге тең?', 'multiple_choice', '"112"'::jsonb, '672 ÷ 6 = 112.', 'Үлкен разрядтан бастап бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('112', true, 0), ('102', false, 1), ('122', false, 2), ('111', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Тексеру теңдігін құрастыр', '480 ÷ 24 = 20 екенін тексеретін көбейту теңдігін құрастыр.', jsonb_build_object('kind', 'expression_builder', 'tiles', jsonb_build_array('24', '×', '20', '=', '480', '440', '460'), 'target', jsonb_build_array('24', '×', '20', '=', '480')), 3 from public.topics where title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '480 ÷ 24 = 20 екенін тексеретін көбейту теңдігін құрастыр.', 'expression_builder', to_jsonb('24 × 20 = 480'::text), '24 × 20 = 480.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Бөлуді сәйкестендір', 'Санды 24-ке бөлгендегі бөлінділерін сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(480,20), jsonb_build_array(240,10), jsonb_build_array(720,30), jsonb_build_array(960,40))), 4 from public.topics where title = 'Көптаңбалы санды бір және екі таңбалы санға бөлу' and grade = 4 and track = 'base';


-- ==== Қалдықпен бөлу (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Бөлу қалдықпен аяқталатын жағдайларды дұрыс есептеу.' where title = 'Қалдықпен бөлу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('29 ÷ 4 = 7 қалдық 1, себебі 4×7=28, ал 29 − 28 = 1.', 'Қалдық әрдайым бөлгіштен кіші болуы керек.')), 0 from public.topics where title = 'Қалдықпен бөлу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Бөлудің қалдығын тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('29', '÷', '4', '=', '7', 'R', '?'), 'blankIndex', 6, 'correctValue', '1'), 0 from public.topics where title = 'Қалдықпен бөлу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Қалдық бөлгіштен үлкен бола ала ма?', 0 from public.topics where title = 'Қалдықпен бөлу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '35 ÷ 6 бөлгенде қандай қалдық шығады?', '{}'::jsonb, 0 from public.topics where title = 'Қалдықпен бөлу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '35 ÷ 6 бөлгенде қандай қалдық шығады?', 'short_answer', '5'::jsonb, '6×5=30, 35−30=5.', '6-ның еселіктерін тізіп шық.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Қалдықпен бөлу' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Қалдықты тап', '47 ÷ 5 бөлгенде қандай қалдық шығады?', 0 from public.topics where title = 'Қалдықпен бөлу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '47 ÷ 5 бөлгенде қандай қалдық шығады?', 'short_answer', '2'::jsonb, '5×9=45, 47−45=2.', '5-тің еселіктерін тізіп шық.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қалдықпен бөлу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Бөлінді табу', '58 ÷ 7 бөлгенде толық бөлінді нешеге тең?', 1 from public.topics where title = 'Қалдықпен бөлу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '58 ÷ 7 бөлгенде толық бөлінді нешеге тең?', 'short_answer', '8'::jsonb, '7×8=56, 58−56=2 қалдық, бөлінді 8.', '7-нің еселіктерін тізіп шық.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қалдықпен бөлу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Қалдықты тап', '52 ÷ 6 бөлгенде қандай қалдық шығады?', 2 from public.topics where title = 'Қалдықпен бөлу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '52 ÷ 6 бөлгенде қандай қалдық шығады?', 'multiple_choice', '"4"'::jsonb, '6×8=48, 52−48=4.', '6-ның еселіктерін тізіп шық.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қалдықпен бөлу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('4', true, 0), ('3', false, 1), ('5', false, 2), ('2', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Қалдықпен бөлу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', '58 ÷ 7 есебінің бөлінді мен қалдығын тексер.', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('7 × 8 = 56', '58 − 56 = 3'), 'errorIndex', 1), 3 from public.topics where title = 'Қалдықпен бөлу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '58 ÷ 7 есебінің бөлінді мен қалдығын тексер.', 'find_error', '1'::jsonb, '58 − 56 = 2, 3 емес.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қалдықпен бөлу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Қалдықты сәйкестендір', 'Санды 7-ге бөлгендегі қалдығымен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(58,2), jsonb_build_array(50,1), jsonb_build_array(45,3), jsonb_build_array(40,5))), 4 from public.topics where title = 'Қалдықпен бөлу' and grade = 4 and track = 'base';


-- ==== Амалдардың орындалу реті және жақшалы өрнектер (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Бірнеше жақшасы бар күрделі өрнектерде амалдардың орындалу ретін білу.' where title = 'Амалдардың орындалу реті және жақшалы өрнектер' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('(12 − 4) × (3 + 2) өрнегінде алдымен әр жақшаны бөлек есептейміз: 12−4=8, 3+2=5, содан кейін 8×5=40.', 'Бірнеше жақша болса, әрқайсысын бөлек есептейміз.')), 0 from public.topics where title = 'Амалдардың орындалу реті және жақшалы өрнектер' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Екі жақшаны бөлек есептеп, өрнектің мәнін тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('(', '12', '−', '4', ')', '×', '(', '3', '+', '2', ')', '=', '?'), 'blankIndex', 12, 'correctValue', '40'), 0 from public.topics where title = 'Амалдардың орындалу реті және жақшалы өрнектер' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Бірнеше жақшасы бар өрнекте қалай есептейміз?', 0 from public.topics where title = 'Амалдардың орындалу реті және жақшалы өрнектер' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '(8 + 2) × (10 − 6) өрнегінің мәнін тап.', '{}'::jsonb, 0 from public.topics where title = 'Амалдардың орындалу реті және жақшалы өрнектер' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '(8 + 2) × (10 − 6) өрнегінің мәнін тап.', 'short_answer', '40'::jsonb, '8+2=10, 10−6=4, 10×4=40.', 'Әр жақшаны бөлек есепте.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Амалдардың орындалу реті және жақшалы өрнектер' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жақшамен есепте', '(15 − 9) × (4 + 1) өрнегінің мәні нешеге тең?', 0 from public.topics where title = 'Амалдардың орындалу реті және жақшалы өрнектер' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '(15 − 9) × (4 + 1) өрнегінің мәні нешеге тең?', 'short_answer', '30'::jsonb, '15−9=6, 4+1=5, 6×5=30.', 'Әр жақшаны бөлек есепте.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Амалдардың орындалу реті және жақшалы өрнектер' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жақшамен есепте', '(6 + 6) ÷ (5 − 2) өрнегінің мәні нешеге тең?', 1 from public.topics where title = 'Амалдардың орындалу реті және жақшалы өрнектер' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '(6 + 6) ÷ (5 − 2) өрнегінің мәні нешеге тең?', 'short_answer', '4'::jsonb, '6+6=12, 5−2=3, 12÷3=4.', 'Әр жақшаны бөлек есепте.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Амалдардың орындалу реті және жақшалы өрнектер' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Жақшамен есепте', '(20 − 8) × (7 − 5) өрнегінің мәні нешеге тең?', 2 from public.topics where title = 'Амалдардың орындалу реті және жақшалы өрнектер' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '(20 − 8) × (7 − 5) өрнегінің мәні нешеге тең?', 'multiple_choice', '"24"'::jsonb, '20−8=12, 7−5=2, 12×2=24.', 'Әр жақшаны бөлек есепте.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Амалдардың орындалу реті және жақшалы өрнектер' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('24', true, 0), ('20', false, 1), ('26', false, 2), ('22', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Амалдардың орындалу реті және жақшалы өрнектер' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', '(15 − 9) × (4 + 1) өрнегінің шешімін тексер.', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('15 − 9 = 6', '4 + 1 = 5', '6 × 5 = 25'), 'errorIndex', 2), 3 from public.topics where title = 'Амалдардың орындалу реті және жақшалы өрнектер' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '(15 − 9) × (4 + 1) өрнегінің шешімін тексер.', 'find_error', '2'::jsonb, '6 × 5 = 30, 25 емес.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Амалдардың орындалу реті және жақшалы өрнектер' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 40 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(15,25), jsonb_build_array(9,31), jsonb_build_array(28,12), jsonb_build_array(6,34))), 4 from public.topics where title = 'Амалдардың орындалу реті және жақшалы өрнектер' and grade = 4 and track = 'base';


-- ==== Теңдеу және күрделі теңдеулерді шешу (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Бірнеше амалы бар күрделі теңдеулерді сатылап шешуді меңгеру.' where title = 'Теңдеу және күрделі теңдеулерді шешу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('3x + 5 = 20 теңдеуін шешу үшін алдымен 5-ті ауыстырамыз: 3x = 15, содан кейін x = 5.', 'Теңдеуді сатылап, қарапайым түрге дейін жеткіземіз.')), 0 from public.topics where title = 'Теңдеу және күрделі теңдеулерді шешу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Күрделі теңдеудегі белгісізді тап.', jsonb_build_object('kind', 'pattern-number', 'sequence', jsonb_build_array('3', '×', '?', '+', '5', '=', '20'), 'blankIndex', 2, 'correctValue', '5'), 0 from public.topics where title = 'Теңдеу және күрделі теңдеулерді шешу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Күрделі теңдеуді шешкенде алдымен нені ауыстырамыз?', 0 from public.topics where title = 'Теңдеу және күрделі теңдеулерді шешу' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '2x + 8 = 24. x неге тең?', '{}'::jsonb, 0 from public.topics where title = 'Теңдеу және күрделі теңдеулерді шешу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '2x + 8 = 24. x неге тең?', 'short_answer', '8'::jsonb, '2x = 24 − 8 = 16, x = 16 ÷ 2 = 8.', 'Алдымен қосылғышты ауыстыр, содан кейін бөл.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Теңдеу және күрделі теңдеулерді шешу' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Күрделі теңдеу', '4x − 6 = 30. x неге тең?', 0 from public.topics where title = 'Теңдеу және күрделі теңдеулерді шешу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '4x − 6 = 30. x неге тең?', 'short_answer', '9'::jsonb, '4x = 36, x = 9.', 'Алдымен азайтылғанды ауыстыр, содан кейін бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Теңдеу және күрделі теңдеулерді шешу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Күрделі теңдеу', '5x + 10 = 45. x неге тең?', 1 from public.topics where title = 'Теңдеу және күрделі теңдеулерді шешу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5x + 10 = 45. x неге тең?', 'short_answer', '7'::jsonb, '5x = 35, x = 7.', 'Алдымен қосылғышты ауыстыр, содан кейін бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Теңдеу және күрделі теңдеулерді шешу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Күрделі теңдеу', '3x − 4 = 20. x неге тең?', 2 from public.topics where title = 'Теңдеу және күрделі теңдеулерді шешу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '3x − 4 = 20. x неге тең?', 'multiple_choice', '"8"'::jsonb, '3x = 24, x = 8.', 'Алдымен азайтылғанды ауыстыр, содан кейін бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Теңдеу және күрделі теңдеулерді шешу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('8', true, 0), ('7', false, 1), ('9', false, 2), ('6', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Теңдеу және күрделі теңдеулерді шешу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қадамды құрастыр', '4x − 6 = 30 теңдеуін шешу қадамын құрастыр: алдымен 4x нешеге тең?', jsonb_build_object('kind', 'expression_builder', 'tiles', jsonb_build_array('30', '+', '6', '=', '36', '28', '40'), 'target', jsonb_build_array('30', '+', '6', '=', '36')), 3 from public.topics where title = 'Теңдеу және күрделі теңдеулерді шешу' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '4x − 6 = 30 теңдеуін шешу қадамын құрастыр: алдымен 4x нешеге тең?', 'expression_builder', to_jsonb('30 + 6 = 36'::text), '4x = 36, x = 9.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Теңдеу және күрделі теңдеулерді шешу' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'x мәнін сәйкестендір', 'x санын 4x нәтижесімен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(9,36), jsonb_build_array(7,28), jsonb_build_array(8,32), jsonb_build_array(6,24))), 4 from public.topics where title = 'Теңдеу және күрделі теңдеулерді шешу' and grade = 4 and track = 'base';


-- ==== Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Жылдамдық, уақыт, қашықтық арасындағы байланысты (кез келген белгісізін табу) есептерде қолдану.' where title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Қашықтық = жылдамдық × уақыт болса, уақыт = қашықтық ÷ жылдамдық, жылдамдық = қашықтық ÷ уақыт.', 'Кез келген екеуін біле отырып, үшіншісін табуға болады.')), 0 from public.topics where title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Бірінші көлік 80 км, екіншісі 60 км жол жүрді (бірдей уақытта). Қайсысы жылдам?', jsonb_build_object('kind', 'compare', 'iconA', 'cube', 'countA', 80, 'iconB', 'cube', 'countB', 60), 0 from public.topics where title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Уақытты табу үшін қашықтықты неге бөлеміз?', 0 from public.topics where title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Көлік 240 км жолды сағатына 60 км жылдамдықпен жүрді. Неше сағат жол жүрді?', '{}'::jsonb, 0 from public.topics where title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Көлік 240 км жолды сағатына 60 км жылдамдықпен жүрді. Неше сағат жол жүрді?', 'short_answer', '4'::jsonb, '240 ÷ 60 = 4 сағат.', 'Қашықтықты жылдамдыққа бөл.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Жылдамдықты тап', 'Ұшақ 1800 км жолды 3 сағатта жүрді. Оның жылдамдығы нешеге тең?', 0 from public.topics where title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Ұшақ 1800 км жолды 3 сағатта жүрді. Оның жылдамдығы нешеге тең?', 'short_answer', '600'::jsonb, '1800 ÷ 3 = 600 км/сағ.', 'Қашықтықты уақытқа бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Қашықтықты тап', 'Пойыз сағатына 90 км жылдамдықпен 5 сағат жүрді. Қанша қашықтыққа жетті?', 1 from public.topics where title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Пойыз сағатына 90 км жылдамдықпен 5 сағат жүрді. Қанша қашықтыққа жетті?', 'short_answer', '450'::jsonb, '90 × 5 = 450 км.', 'Жылдамдықты уақытқа көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Уақытты тап', 'Көлік 350 км жолды сағатына 70 км жылдамдықпен жүрді. Неше сағат жол жүрді?', 2 from public.topics where title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Көлік 350 км жолды сағатына 70 км жылдамдықпен жүрді. Неше сағат жол жүрді?', 'multiple_choice', '"5"'::jsonb, '350 ÷ 70 = 5 сағат.', 'Қашықтықты жылдамдыққа бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('5', true, 0), ('4', false, 1), ('6', false, 2), ('7', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'ordering', 'Өсу ретімен тіз', 'Нәтижелерді өсу ретімен тіз: 350 ÷ 70, 90 × 5, 1800 ÷ 3.', jsonb_build_object('items', jsonb_build_array('5', '450', '600')), 3 from public.topics where title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Уақыт пен қашықтықты сәйкестендір', 'Жылдамдығы 60 км/сағ болғанда, уақытты сол уақытта жүрген қашықтықпен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(1,60), jsonb_build_array(2,120), jsonb_build_array(3,180), jsonb_build_array(4,240))), 4 from public.topics where title = 'Қозғалысқа байланысты есептер: жылдамдық, уақыт, қашықтық' and grade = 4 and track = 'base';


-- ==== Бірнеше шаманың арасындағы тәуелділік (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Баға, саны, құн сияқты бірнеше шаманың бір-біріне тәуелділігін түсініп есептерде қолдану.' where title = 'Бірнеше шаманың арасындағы тәуелділік' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Құн = баға × саны. Бір қаламның бағасы 50 теңге болса, 4 қалам 200 теңге тұрады.', 'Осы үш шаманың кез келген екеуін біліп, үшіншісін табуға болады.')), 0 from public.topics where title = 'Бірнеше шаманың арасындағы тәуелділік' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Екі есептеу нәтижесін салыстыр (тең бе?).', jsonb_build_object('kind', 'value-compare', 'labelA', 'Баға × саны', 'labelB', 'Құн', 'numericA', 200, 'numericB', 200), 0 from public.topics where title = 'Бірнеше шаманың арасындағы тәуелділік' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Құн, баға және санның арасындағы байланыс қандай формуламен өрнектеледі?', 0 from public.topics where title = 'Бірнеше шаманың арасындағы тәуелділік' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Бір дәптердің бағасы 45 теңге. 6 дәптердің құны нешеге тең?', '{}'::jsonb, 0 from public.topics where title = 'Бірнеше шаманың арасындағы тәуелділік' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Бір дәптердің бағасы 45 теңге. 6 дәптердің құны нешеге тең?', 'short_answer', '270'::jsonb, '45 × 6 = 270 теңге.', 'Бағаны санына көбейт.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Бірнеше шаманың арасындағы тәуелділік' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Бағасын тап', '8 қаламның құны 320 теңге. Бір қаламның бағасы нешеге тең?', 0 from public.topics where title = 'Бірнеше шаманың арасындағы тәуелділік' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '8 қаламның құны 320 теңге. Бір қаламның бағасы нешеге тең?', 'short_answer', '40'::jsonb, '320 ÷ 8 = 40 теңге.', 'Құнды санына бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Бірнеше шаманың арасындағы тәуелділік' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Санын тап', 'Бір кітаптың бағасы 120 теңге. 600 теңгеге неше кітап сатып алуға болады?', 1 from public.topics where title = 'Бірнеше шаманың арасындағы тәуелділік' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Бір кітаптың бағасы 120 теңге. 600 теңгеге неше кітап сатып алуға болады?', 'short_answer', '5'::jsonb, '600 ÷ 120 = 5 кітап.', 'Ақшаны бағаға бөл.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Бірнеше шаманың арасындағы тәуелділік' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Құнын тап', 'Бір алманың бағасы 25 теңге. 8 алманың құны нешеге тең?', 2 from public.topics where title = 'Бірнеше шаманың арасындағы тәуелділік' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Бір алманың бағасы 25 теңге. 8 алманың құны нешеге тең?', 'multiple_choice', '"200"'::jsonb, '25 × 8 = 200 теңге.', 'Бағаны санына көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Бірнеше шаманың арасындағы тәуелділік' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('200', true, 0), ('180', false, 1), ('220', false, 2), ('175', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Бірнеше шаманың арасындағы тәуелділік' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'drag_drop', 'Амалды ажырат', 'Әр есепте бөлу немесе көбейту керек екенін ажырат.', jsonb_build_object('items', jsonb_build_array(jsonb_build_object('label', '8 қаламның құны 320 теңге, бір қаламның бағасы?', 'group', 'a'), jsonb_build_object('label', 'Бір алманың бағасы 25 теңге, 8 алманың құны?', 'group', 'b'), jsonb_build_object('label', 'Бір дәптердің бағасы 45 теңге, 6 дәптердің құны?', 'group', 'b'), jsonb_build_object('label', '600 теңгеге 120 теңгелік кітаптан неше сатып алуға болады?', 'group', 'a')), 'groupALabel', 'Бөлу керек', 'groupBLabel', 'Көбейту керек'), 3 from public.topics where title = 'Бірнеше шаманың арасындағы тәуелділік' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Санды құнымен сәйкестендір', 'Бір заттың бағасы 45 теңге болғанда, санын жалпы құнымен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(2,90), jsonb_build_array(4,180), jsonb_build_array(6,270), jsonb_build_array(8,360))), 4 from public.topics where title = 'Бірнеше шаманың арасындағы тәуелділік' and grade = 4 and track = 'base';


-- ==== Бөлшек ұғымы және бөлшектерді салыстыру (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Бөлшек ұғымын (алымы, бөлімі) түсініп, бірдей бөлімді бөлшектерді салыстыру.' where title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('3/4 бөлшегінде 3 — алым, 4 — бөлім. Бұл бүтіннің 4 бөлігінің 3-ін білдіреді.', 'Бөлімдері бірдей бөлшектерде алымы үлкені — үлкен бөлшек: 3/5 > 2/5.')), 0 from public.topics where title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Бөлімдері бірдей екі бөлшектің алымдарын салыстыр.', jsonb_build_object('kind', 'value-compare', 'labelA', '3/5', 'labelB', '2/5', 'numericA', 3, 'numericB', 2), 0 from public.topics where title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Бөлімдері бірдей бөлшектерде қайсысы үлкен болады?', 0 from public.topics where title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', '5/8 бен 3/8 бөлшектерінің қайсысы үлкен? (алымын жаз)', '{}'::jsonb, 0 from public.topics where title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '5/8 бен 3/8 бөлшектерінің қайсысы үлкен? (алымын жаз)', 'short_answer', '5'::jsonb, '5/8 > 3/8, себебі 5 > 3.', 'Алымдарын салыстыр.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Бөлшекті салыстыр', '7/10 бен 4/10 бөлшектерінің қайсысы кіші? (алымын жаз)', 0 from public.topics where title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '7/10 бен 4/10 бөлшектерінің қайсысы кіші? (алымын жаз)', 'short_answer', '4'::jsonb, '4/10 < 7/10, себебі 4 < 7.', 'Алымдарын салыстыр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Алымын тап', '1/4 бөлшегінің алымы нешеге тең?', 1 from public.topics where title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '1/4 бөлшегінің алымы нешеге тең?', 'short_answer', '1'::jsonb, '1/4 бөлшегінде алымы 1.', 'Бөлшектің жоғарғы саны — алым.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Бөлшекті салыстыр', '6/9 бен 4/9 бөлшектерінің қайсысы үлкен?', 2 from public.topics where title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, '6/9 бен 4/9 бөлшектерінің қайсысы үлкен?', 'multiple_choice', '"6/9"'::jsonb, '6/9 > 4/9, себебі 6 > 4.', 'Алымдарын салыстыр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('6/9', true, 0), ('4/9', false, 1), ('тең', false, 2), ('білмеймін', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'ordering', 'Өсу ретімен тіз', 'Бөлшектерді өсу ретімен тіз: 6/9, 2/9, 4/9.', jsonb_build_object('items', jsonb_build_array('2/9', '4/9', '6/9')), 3 from public.topics where title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Алымды толықтырушысымен сәйкестендір', 'Алымды 10-ға толықтыратын санмен сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(3,7), jsonb_build_array(4,6), jsonb_build_array(2,8), jsonb_build_array(1,9))), 4 from public.topics where title = 'Бөлшек ұғымы және бөлшектерді салыстыру' and grade = 4 and track = 'base';


-- ==== Тік төртбұрыш пен шаршының ауданы және периметрі (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Тіктөртбұрыш пен шаршының ауданы мен периметрін бірге есептеп, олардың арасындағы байланысты түсіну.' where title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'infographic', null, null, jsonb_build_object('kind', 'scene', 'items', jsonb_build_array(jsonb_build_object('icon', '⬛', 'label', 'Шаршы (периметр = қабырға × 4)'), jsonb_build_object('icon', '▬', 'label', 'Тіктөртбұрыш (периметр = 2×(ені+ұзындығы))')), 'caption', 'Ені 8 см, ұзындығы 5 см тіктөртбұрыштың периметрі 2×(8+5)=26 см, ауданы 8×5=40 шаршы см. Периметрі бірдей екі фигураның аудандары әртүрлі болуы мүмкін.'), 0 from public.topics where title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Тіктөртбұрыштың ауданын тап.', jsonb_build_object('kind', 'area', 'width', 8, 'height', 5, 'unit', 'см'), 0 from public.topics where title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Периметрі бірдей екі фигураның аудандары да бірдей бола ма?', 0 from public.topics where title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Ені 9 см, ұзындығы 4 см тіктөртбұрыштың ауданын тап.', '{}'::jsonb, 0 from public.topics where title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Ені 9 см, ұзындығы 4 см тіктөртбұрыштың ауданын тап.', 'short_answer', '36'::jsonb, '9 × 4 = 36 шаршы см.', 'Ені мен ұзындықты көбейт.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Периметрін тап', 'Ені 9 см, ұзындығы 4 см тіктөртбұрыштың периметрі нешеге тең?', 0 from public.topics where title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Ені 9 см, ұзындығы 4 см тіктөртбұрыштың периметрі нешеге тең?', 'short_answer', '26'::jsonb, '2 × (9 + 4) = 26 см.', 'Ені мен ұзындықты қосып, 2-ге көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Ауданын тап', 'Қабырғасы 12 см шаршының ауданы нешеге тең?', 1 from public.topics where title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Қабырғасы 12 см шаршының ауданы нешеге тең?', 'short_answer', '144'::jsonb, '12 × 12 = 144 шаршы см.', 'Қабырғаны өзіне көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Периметрін тап', 'Қабырғасы 12 см шаршының периметрі нешеге тең?', 2 from public.topics where title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Қабырғасы 12 см шаршының периметрі нешеге тең?', 'multiple_choice', '"48"'::jsonb, '12 × 4 = 48 см.', 'Қабырғаны 4-ке көбейт.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('48', true, 0), ('36', false, 1), ('60', false, 2), ('144', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Ұзындықты өлш', 'Тіктөртбұрыштың ұзындығын сызғышпен өлш.', jsonb_build_object('kind', 'measurement', 'unit', 'см', 'length', 8, 'maxScale', 12), 3 from public.topics where title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Тіктөртбұрыштың ұзындығын сызғышпен өлш.', 'measurement', '8'::jsonb, 'Сызғыш бойынша ұзындық 8 см.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Периметрді сәйкестендір', 'Шаршының қабырғасын оның периметрімен сәйкестендір (қабырға × 4):', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(5,20), jsonb_build_array(8,32), jsonb_build_array(9,36), jsonb_build_array(12,48))), 4 from public.topics where title = 'Тік төртбұрыш пен шаршының ауданы және периметрі' and grade = 4 and track = 'base';


-- ==== Күрделі, логикалық және стандартты емес мәтінді есептер (4-сынып, base) ====
update public.topics set status = 'published', learning_objective = 'Стандартты емес, күрделі логикалық мәтін есептерді талдап, шешу жолын өз бетінше құру.' where title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, media_url, configuration, sort_order)
select id, 'kor', 'text', null, null, jsonb_build_object('kind', 'story', 'slides', jsonb_build_array('Кейбір есептерде тікелей формула жоқ, алдымен есептің логикасын түсіну керек.', 'Мысалы: «Екі санның қосындысы 20, көбейтіндісі 91» — сынап көру арқылы шешіледі: 7 және 13 (7+13=20, 7×13=91).')), 0 from public.topics where title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qurastyr', 'number_builder', 'Қосындысы 20, көбейтіндісі 91 болатын екі санды таптық: 7 және 13. Қайсысы үлкен?', jsonb_build_object('kind', 'compare', 'iconA', 'star', 'countA', 7, 'iconB', 'star', 'countB', 13), 0 from public.topics where title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, sort_order)
select id, 'tusindir', 'short_answer', 'Стандартты емес есепте тікелей формула болмаса, қандай тәсіл қолданамыз?', 0 from public.topics where title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and grade = 4 and track = 'base';

insert into public.lesson_blocks (topic_id, stage, block_type, content, configuration, sort_order)
select id, 'qoldan', 'question', 'Екі санның қосындысы 15, көбейтіндісі 56. Кіші санды тап.', '{}'::jsonb, 0 from public.topics where title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Екі санның қосындысы 15, көбейтіндісі 56. Кіші санды тап.', 'short_answer', '7'::jsonb, '7 және 8: 7+8=15, 7×8=56, кіші сан — 7.', 'Қосындысы 15 болатын жұптарды сынап көр.', 1 from public.lesson_blocks lb join public.topics tp on tp.id = lb.topic_id where tp.title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and tp.grade = 4 and tp.track = 'base' and lb.stage = 'qoldan';

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Санды тап', 'Екі санның қосындысы 12, көбейтіндісі 35. Үлкен санды тап.', 0 from public.topics where title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Екі санның қосындысы 12, көбейтіндісі 35. Үлкен санды тап.', 'short_answer', '7'::jsonb, '5 және 7: 5+7=12, 5×7=35, үлкен сан — 7.', 'Қосындысы 12 болатын жұптарды сынап көр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 0;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'short_answer', 'Логикалық есеп', 'Үш дос конфет бөлісті: біріншісі екіншісінен 2-ге көп, үшіншісі біріншісінен 3-ке көп алды. Екіншісі 4 конфет алса, үшіншісі неше конфет алды?', 1 from public.topics where title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Үш дос конфет бөлісті: біріншісі екіншісінен 2-ге көп, үшіншісі біріншісінен 3-ке көп алды. Екіншісі 4 конфет алса, үшіншісі неше конфет алды?', 'short_answer', '9'::jsonb, 'Бірінші = 4+2=6, үшінші = 6+3=9.', 'Алдымен бірінші достың санын тап.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 1;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, sort_order)
select id, 'bekit', 'multiple_choice', 'Санды тап', 'Екі санның қосындысы 18, көбейтіндісі 77. Кіші санды тап.', 2 from public.topics where title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Екі санның қосындысы 18, көбейтіндісі 77. Кіші санды тап.', 'multiple_choice', '"7"'::jsonb, '7 және 11: 7+11=18, 7×11=77, кіші сан — 7.', 'Қосындысы 18 болатын жұптарды сынап көр.', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.question_options (question_id, option_text, is_correct, sort_order)
select q.id, opt.text, opt.is_correct, opt.ord from public.questions q join public.lesson_blocks lb on lb.id = q.lesson_block_id join public.topics t2 on t2.id = lb.topic_id cross join (values ('7', true, 0), ('9', false, 1), ('11', false, 2), ('6', false, 3)) as opt(text, is_correct, ord) where t2.title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 2;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'question', 'Қатені тап', 'Екі санның қосындысы 12, көбейтіндісі 35 есебінің шешімін тексер.', jsonb_build_object('kind', 'find_error', 'steps', jsonb_build_array('5 және 7 сандарын сынап көрейік', '5 + 7 = 12, 5 × 7 = 36'), 'errorIndex', 1), 3 from public.topics where title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and grade = 4 and track = 'base';

insert into public.questions (lesson_block_id, question_text, question_type, correct_answer, explanation, hint, points)
select lb.id, 'Екі санның қосындысы 12, көбейтіндісі 35 есебінің шешімін тексер.', 'find_error', '1'::jsonb, '5 × 7 = 35, 36 емес.', '', 1 from public.lesson_blocks lb join public.topics t2 on t2.id = lb.topic_id where t2.title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and t2.grade = 4 and t2.track = 'base' and lb.stage = 'bekit' and lb.sort_order = 3;

insert into public.lesson_blocks (topic_id, stage, block_type, title, content, configuration, sort_order)
select id, 'bekit', 'matching', 'Жұптарды сәйкестендір', 'Қосындысы 20 болатын сандарды сәйкестендір:', jsonb_build_object('pairs', jsonb_build_array(jsonb_build_array(12,8), jsonb_build_array(15,5), jsonb_build_array(9,11), jsonb_build_array(13,7))), 4 from public.topics where title = 'Күрделі, логикалық және стандартты емес мәтінді есептер' and grade = 4 and track = 'base';

